### ISSUE TITLE
SkiaSharp renderer

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#1]
As far as I can see, this project is limited to Xamarin.iOS only. However, for most people, the reason for choosing Xamarin instead of native Swift/Kotlin is code sharing with C#. Also, as time goes by, the Xamarin.Forms approach is slowly overshadowing Xamarin native. If this library can have Xamarin.Forms support, then we have a viable competitor to the MathJax/KaTeX + WebView approach, which is slow and RAM-consuming.

I can think of two approaches to this now:
1) Use each platform's native APIs (6 platforms to support, so very time-consuming)
2) Use Xamarin.Forms BoxViews with rotation (Might need very hacky ways to do this)

So, although both approaches are not very good, once Xamarin.Forms is supported, then:
1) MathJax/KaTeX + WebView approach can be considered deprecated
2) Popularity boost for this project!

P.S. Before you ask, I don't really know Xamarin.iOS/native iOS APIs well, so currently I can't really help you here.

**Comment by verybadcat** [comment]
What I am doing is designing it so that the front end can be plugged in. I don't know the relevant Api too well either -- likely SkiaSharp and/or HarfBuzz. But I'm setting things up so that to create a front end, you have to define your own TypesettingContext and GraphicsContext objects, but you do NOT need to go into the Typesetter code. In other words, the process of creating a front end should be limited to telling it how to measure glyphs and what spacings you want around them. This is still a nontrivial task, but it's a lot less than writing the whole system.

So yeah, if someone starts on that for Xamarin.Forms, I will be thrilled.

**Comment by Happypig375** [comment]
@verybadcat 
I want to help with this, however a hit a very big problem:
I cannot find any framework methods in Android/UWP for direct font manipulation.
This is frustrating.

So, maybe instead of loading a otf file at runtime, encode the glyphs in byte arrays and treat them as bitmaps, and draw the bitmaps directly, which most platforms should support.

Any thoughts?

**Comment by verybadcat** [comment]
I seem to remember somewhere that .otf files won't work on non-Apple formats. But there has to be a way to load a font. I also wonder if their default fonts have the needed characters.

Incidentally, another way to help the project would be to get more people interested.

**Comment by Happypig375** [comment]
So far my comment at https://github.com/Microsoft/xaml-standard/issues/192#issuecomment-356966958 has not gained any traction...

**Comment by Happypig375** [comment]
Yay! This repository now has 3 more stars. Hope that this growth can keep going...

**Comment by Happypig375** [comment]
From a deleted comment (https://github.com/Microsoft/xaml-standard/issues/192#issuecomment-357988086):

>Starting with Android API 26, fonts can be loaded as resources in Xamarin Android projects.
https://developer.xamarin.com/guides/android/application_fundamentals/resources_in_android/part_7_-_fonts/

**Comment by Happypig375** [comment]
Ayyy, another mention: https://forums.xamarin.com/discussion/4483/math-type-mathjax-for-displaying-equations

**Comment by tilutza** [comment]
hello,

I can assist you in porting this to Xamarin Forms. You could to this in many ways:
- using a library like Skia or anything similar. I do not have experience in this, but I have no experience in this
- implement for each platform. Since you have already the support for iOS, you could add something for Android and use native Canvas from Android.

**Comment by Happypig375** [comment]
@verybadcat Another C# LaTeX library for reference: https://github.com/ForNeVeR/wpf-math

**Comment by zwcloud** [comment]
@Happypig375 For font manipulation, I recommend [Typography](https://github.com/LayoutFarm/Typography) or  [sixlabors/fonts](https://github.com/sixlabors/fonts).

**Comment by verybadcat** [comment]
@tilutza just noticed your comment. I would love to get this onto forms.

**Comment by charlesroddie** [comment]
I could work with @tilutza and @Happypig375 on SkiaSharp support.

**Comment by verybadcat** [comment]
Terrific. What do y'all need from me to get started? I can certainly give you access to the repo; all I would ask is that you do it in a project on top of the existing ones.

**Comment by Happypig375** [comment]
@charlesroddie Can you lay out the plans? Probably a table with assignees to avoid duplication of work.

@tilutza Please comment on this.

**Comment by charlesroddie** [comment]
I will need to read through the CSharpMath code first before making a plan.

The first thing can be scaffolding: on a new branch we need a separate main project for SkiaSharp (with no Xamarin.Forms dependency), and then Xamarin.Forms sample projects (a .net standard library, and platform-specific projects for UWP, iOS, Android). I think we can work with .net standard 2.0 everywhere. Can one of you make a start on this?

This would allow the project to be used for non-XF projects including WPF, Xamarin without forms, UWP, and anywhere else SkiaSharp is used.

I have done LaTeX parsing and have some familiarity with SkiaSharp. My C# is basic.

**Comment by Happypig375** [comment]
I have pushed a new branch with a new project and dependencies.

I don't think we can declare SkiaSharp views in a .NET Standard project. We can declare them in platform projects though. Should we make little platform projects that reference the appropriate SkiaSharp platforms and share a shared project among them?

**Comment by Happypig375** [comment]
Ayyy, you are here! 😃

**Comment by charlesroddie** [comment]
"SkiaSharp provides cross-platform bindings for: ... .NET Standard 1.3..."

**Comment by Happypig375** [comment]
>"SkiaSharp provides cross-platform bindings for: ... .NET Standard 1.3..."

SKSurface etc. are there, but no SKViews.
If we go the .NET Standard route, we may have to require the end user to call a method returning an SKSurface and bind it to the native SKView themselves.

**Comment by charlesroddie** [comment]
That's fine for the moment. That should just be a couple of lines of code.

**Comment by tilutza** [comment]
I am glad that there are people interested to port this, but my availability is quite limited. However, I would help in terms of decisions, architecture and advises (in the thread or in a chat room).

Regarding using SkiaSharp I think it's a very goo option. I see that there are binding from using .NET Stardard already (referencing Xamarin Forms) https://github.com/mono/SkiaSharp/tree/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.NetStandard

There are ways using directly from xamarin firms as presented in the official documentation https://developer.xamarin.com/api/namespace/SkiaSharp.Views.Forms/

However I am no expert in manipulating fonts (just to use them), and my experience in drawing is to do it on a Canvas. There are a couple of things which are not clear for me:
- what does the Font Mapping Map to help to draw on a canvas

**Comment by Happypig375** [comment]
Btw, have you accepted the collaborator invitation?

**Comment by verybadcat** [comment]
Based on what @tilutza wrote above, I'm not inviting him yet, but I'm happy to do so if it should become helpful.

SkiaSharp does work on Xamarin.Forms with .netstandard. The only question would be whether it has a font with all the math glyphs.

**Comment by charlesroddie** [comment]
I can only see the font latinmodern-math.otf in this repo. It may work but presumably we could fall back on a truetype version if it doesn't.

**Comment by verybadcat** [comment]
I don't think .otf works on non-Apple platforms.

**Comment by ForNeVeR** [comment]
@verybadcat 
> I don't think .otf works on non-Apple platforms.

Actually, Windows does support OTF. It looks like [Linux support it](https://askubuntu.com/questions/18357/how-to-install-otf-fonts), too. Although I don't know how widespread the support is on mobile platforms.

**Comment by Happypig375** [comment]
[Android supports OTF too.](http://www.technetexperts.com/mobile/using-external-fonts-in-android-view/)
[All major Android browsers support it](https://caniuse.com/#feat=ttf), so I guess it is pretty widespread.

Therefore:

Platform|Supported?
-|-
Windows|[:heavy_check_mark:](#issuecomment-364822294)
Linux|[:heavy_check_mark:](#issuecomment-364822294)
Mac|[:heavy_check_mark:](#issuecomment-356953443)
iOS|[:heavy_check_mark:](#issuecomment-356953443)
Android|:heavy_check_mark:

Great.

**Comment by Happypig375** [comment]
I just pushed another commit with a new Forms project to implement the actual view. The view delegates the PaintSurface call to SkiaLatexPainter which will be made to paint LaTeX on the provided SKSurfave with provided SKImageInfo.

**Comment by Happypig375** [comment]
I really think a cross-platform typesetting library is much needed.

Three contenders:
https://github.com/SixLabors/Fonts
Pro: Small & fast
Con: No OTF support?

https://github.com/LayoutFarm/Typography
Pro: OTF in C#!!!
Con: Worrying license (according to [this](https://github.com/verybadcat/CSharpMath/issues/2#issuecomment-353904523))

https://github.com/harfbuzz/harfbuzz
Pro: Fast & widely used & designed to work with SkiaSharp and Xamarin (according to [this](https://github.com/verybadcat/CSharpMath/issues/2#issuecomment-353904523))
Con: C++, not C#

Any thoughts?

**Comment by Happypig375** [comment]
Btw, 3rd commit with initial SkiaGraphicsContext. Stuck until above is resolved.

**Comment by charlesroddie** [comment]
You made a quick start @Happypig375 ! I haven't been able to put time into this yet but will find time over the next week to get going.

Regarding fonts: the problem is to do with analysing fonts rather than rendering? That doesn't have to be done on the user system does it? If not, the language doesn't matter and copyleft licenses don't matter either, and the platform shouldn't matter either, unless there are platform-specific bugs in rendering.

**Comment by Happypig375** [comment]
4th commit: Typography submodule
There isn't a NuGet package for Typography so I used a submodule.
I am not using the most updated commit according to [this](https://github.com/LayoutFarm/Typography/issues/96#issuecomment-366190973)

**Comment by prepare** [comment]
Hello, 
> https://github.com/LayoutFarm/Typography
> ...
> Con: Worrying license (according to this)


Why do you worry about  a [license](https://github.com/LayoutFarm/Typography/blob/master/LICENSE.md) of Typography ?

**Comment by Happypig375** [comment]
@prepare, it is not me who is worried about the license, this is just a conclusion from @verybadcat's comment which I quoted.

**Comment by ForNeVeR** [comment]
Let's move the license discussion to https://github.com/LayoutFarm/Typography/issues/97

**Comment by Happypig375** [comment]
5th commit: Currently implementing GlyphFinder 
Added reference to Typography.OpenFont and Typography.GlyphLayout shared projects in CSharpMath.SkiaSharp
Changed NuGet package: SkiaSharp.Views to SkiaSharp

**Comment by verybadcat** [comment]
In my iOS version, the end user creates an IosMathLabel object. So I don't see that as the end of the world. Additionally, there are ways to work around such issues with dependency injection and/or factories.

**Comment by Happypig375** [comment]
6th commit: Further development; a number of interfaces implemented. Awaiting new version of Typography to support Glyph names (LayoutFarm/Typography#98); still have errors occurring; looking good though.

**Comment by Happypig375** [comment]
7th commit: Referenced Typography.Contours and Demo Shared Project to implement glyph rendering
Implementing glyph rendering

**Comment by Happypig375** [comment]
8th commit:
SkiaGraphicsContext done
Minor cleanup of interfaces

**Comment by charlesroddie** [comment]
Having trouble loading the SkiaSharp project because it can't find Typography.

Possibly interesting: https://github.com/mono/SkiaSharp/releases/tag/v1.60.0

HarfBuzzSharp (preview)
HarfBuzz is a text shaping engine, and HarfBuzzSharp exposes some of the functionality to managed .NET applications.

SkiaSharp.HarfBuzz (preview)
Support for text shaping using the HarfBuzz text shaping library. This package adds the SKShaper type that can shape a string, returning the codepoints and their positions.

This package also adds some extension methods to SKCanvas to make drawing shaped text easier. These methods include DrawShapedText and it's overloads.

**Comment by Happypig375** [comment]
Have you cloned the repo with `--recurse-submodules`?
Like this: `git clone --recurse-submodules -b SkiaSharp https://github.com/verybadcat/CSharpMath.git`
It will auto-initialize the submodules, which is Typography in this case.
If submodules are not initialized, then the Typography folder will be empty, which Visual Studio then cannot load.

---

Have you noticed how small SkiaSharp.HarfBuzz is? It is too small that I would probably need to implement a lot more than now.
SKTypeface is also not enough as it requires you to literally parse the bytes from an OTF table yourself, which Typography has this built-in, with a lot of convenient functions to help with typography work (no pun intended).

**Comment by charlesroddie** [comment]
Thanks!

**Comment by verybadcat** [comment]
Just a note that I'm still around and I check this every so often. I can also be reached at [my last name]@gmail.com, if you need me.

**Comment by Happypig375** [comment]
@verybadcat
The current situation is that I am awaiting Typography to support reading CTF tables in OTF files. @prepare said that he was going to take a 2-week break starting from 26th February, but I have not seen any action since then.

**Comment by ForNeVeR** [comment]
@charlesroddie I would be happy to provide you any details and any possible help after I develop the corresponding functionality for WPF-Math. I can't say that it's on my nearest-TODO list though.

**Comment by Happypig375** [comment]
9th commit: Typography has done its APIs, Back to work; Implemented most of the Interfaces

**Comment by Happypig375** [comment]
10th commit: Use new GetGlyphByName submitted to Typography in SkiaGlyphNameProvider

**Comment by Happypig375** [comment]
12th commit: Started implementing SkiaLatexPainter

**Comment by Happypig375** [comment]
13th commit: Started debugging phase; bug discovered in Typography?

**Comment by Happypig375** [comment]
14th commit: Created a new CSharpMath.Utils project to generate Otf.cs, a file that is really, really big in size.

**Comment by Happypig375** [comment]
15th commit: Updated Typography submodule to incorporate the changes I made.

16th commit: Merged local and remote because I forgot to update the repo on the other computer 😛

Now builds without errors and runs without TypeLoadExceptions.
Still needs to figure out why nothing is bring displayed though.

**Comment by Happypig375** [comment]
17th commit: Improved glyph rendering code; now renders something -- inverted glyphs, and overlapped together. Some more debugging to go...

**Comment by Happypig375** [comment]
18th commit: Starting Beta phase; @charlesroddie please take a look.

**Comment by Happypig375** [comment]
19th commit: Separated CSharpMath.Forms to CSharpMath.Forms and CSharpMath.Forms.Example

**Comment by Happypig375** [comment]
20th commit: CSharpMath core project now targets .NET Standard 1.3.

**Comment by Happypig375** [comment]
21th commit: CSharpMath.Forms.Example is now available for testing; More bugfixes

Still more bugfixes to go...
![image](https://user-images.githubusercontent.com/19922066/40266628-a0a61be0-5b81-11e8-9aa8-d67d9481b739.png)

**Comment by Happypig375** [comment]
22th commit: Improved the example and fixed bugs related to re-assigning properties of SkiaLatexPainter and FormsLatexView

![image](https://user-images.githubusercontent.com/19922066/40276154-f88c5ad2-5c34-11e8-88f3-95b012e05802.png)

**Comment by Happypig375** [comment]
23th commit: Added a page to the example for custom LaTeX input

**Comment by Happypig375** [comment]
25th commit: Added toggle for drawing string boxes; the red lines (glyph advances) are of interest.
![image](https://user-images.githubusercontent.com/19922066/40307646-f2f28f2c-5d35-11e8-94ae-678b7f9a4c31.png)

**Comment by Happypig375** [comment]
26th commit: Fixed the glyph bounds provider with the Typography update

@verybadcat I am going to rewrite FontMathTable.cs in the next few commits. If that is not okay, please reply.

**Comment by Happypig375** [comment]
27th commit: SkiaMathTable with Typography's MathTable

**Comment by Happypig375** [comment]
25th commit: Fixed some bugs; displayed math now more readable
![image](https://user-images.githubusercontent.com/19922066/40422164-fd5205ba-5ec0-11e8-9961-010c011ae2c2.png)

**Comment by Happypig375** [comment]
29th commit: Added bindable properties to FormsLatexView

**Comment by Happypig375** [comment]
30th commit: Minor bug fixes; corrected red bounding boxes in example

**Comment by Happypig375** [comment]
31st commit: Added vertical text alignment

**Comment by Happypig375** [comment]
32nd commit: Example running on Android!
![image](https://user-images.githubusercontent.com/19922066/40575043-183a6970-6110-11e8-887f-820e14efc588.jpeg)

**Comment by Happypig375** [comment]
33rd commit: Bugfix for \sqrt with Typography update

**Comment by Happypig375** [comment]
25th commit: Nested radicals now fixed
![image](https://user-images.githubusercontent.com/19922066/40587215-b96a3f52-61fe-11e8-9b13-f9a6e55e7195.png)

**Comment by Happypig375** [comment]
36th commit: Example on iOS Simulator; experimental draggable FormsLatexView
![image](https://user-images.githubusercontent.com/19922066/40612166-fd6c5b38-62ab-11e8-9cb1-b2b7eb6883be.png)

**Comment by prepare** [comment]
'gesture input' => 'math glyph' => math equation!

I'm waiting for that :)

**Comment by Happypig375** [comment]
38th commit: Use Path Stack to store paths instead of directly drawing to Canvas

**Comment by Happypig375** [comment]
39th commit: Fully pannable FormsLatexView! <br/>
![2ba7ya](https://user-images.githubusercontent.com/19922066/40731183-18a09b68-6463-11e8-8095-1a4cc9df9eae.gif)

**Comment by Happypig375** [comment]
40th commit: Pinchable FormsLatexView!
![image](https://user-images.githubusercontent.com/19922066/40779714-9340bd08-6508-11e8-9bda-553d830225ee.png)

**Comment by prepare** [comment]
@Happypig375 , it is too small image.

**Comment by Happypig375** [comment]
@prepare Fixed!

**Comment by Happypig375** [comment]
41th commit: Merge bugfix by @verybadcat concerning the nested \sqrt bug

**Comment by Happypig375** [comment]
42th commit: The ability to lock gestures in FormsLatexView and more bugfixes

**Comment by Happypig375** [comment]
43th commit: Added LineStyle so default mode of display can be set

**Comment by Happypig375** [comment]
44th commit: Added color settings to Example

**Comment by Happypig375** [comment]
45th commit: Added more settings to Example <br/>
Look at this craziness 😆
![Green all examples page](https://user-images.githubusercontent.com/19922066/40888145-4fc7166a-6785-11e8-9351-738188c4d68e.jpeg)
![Corresponding settings](https://user-images.githubusercontent.com/19922066/40888149-5e68be6c-6785-11e8-9178-27000763f9df.jpeg)

**Comment by prepare** [comment]
Why ??

![missing_1](https://user-images.githubusercontent.com/7447159/40891632-76437ca6-67b3-11e8-876b-c20b39d313e8.jpeg)

**Comment by Happypig375** [comment]
Will take a look.

**Comment by Happypig375** [comment]
46th commit: Starting to implement \color

**Comment by Happypig375** [comment]
47th commit: Good results, need to fix horizontal advance though
@prepare Unfortunately the glyphs are still not fixed. (Drawing path from final point to initial point does not help.) Will take a look again later.

![image](https://user-images.githubusercontent.com/19922066/40972206-8abc247c-68f2-11e8-8684-561b5e833c21.png)

**Comment by Happypig375** [comment]
48th commit: Fixed contours of glyphs (thanks @prepare), disabled android Example tabbed page swiping

**Comment by Happypig375** [comment]
49th commit: In process of fixing \color

**Comment by Happypig375** [comment]
50th commit: Added MathSource which will be extensible to more sources!

**Comment by Happypig375** [comment]
51th commit: Renamed all LatexViews to MathViews because it sounds less restrictive
(At the same time, scrolling them got slower again, will fix)

**Comment by Happypig375** [comment]
52nd commit: README now has much more information!

**Comment by Happypig375** [comment]
53rd commit: Adding file I/O to Example

**Comment by charlesroddie** [comment]
Very nice work @Happypig375 . The SkiaSharp renderer part looks close to packageable. I have not been able to help on this, but I can give you an internship to work on this and related open source .net latex projects if you would like. Just send me an email.

**Comment by Happypig375** [comment]
54th commit: Preparation for an icon for CSharpMath

**Comment by Happypig375** [comment]
55th commit: First iteration of the CSharpMath icon
![icon](https://user-images.githubusercontent.com/19922066/41346611-9e5fb0a0-6f39-11e8-8f33-4a4972555802.png)

Comments and suggestions are much appreciated!
Since colors are now supported through \color, posts regarding adding colors can be made too.

**Comment by Happypig375** [comment]
56th~61th commit: Merged the 'Features/Multi-Typefaces' branch into 'SkiaSharp' branch, but created unnecessary commits due to misuse of git rebase

**Comment by Happypig375** [comment]
63rd commit: A new 'More Examples' page with examples imported from iosMath

Also discovered an exception surroundsing 'f(x) = \int\limits_{-\infty}^\infty\!\hat f(\xi)\,e^{2 \pi i \xi x}\,\mathrm{d}\xi' where the \hat causes some bugs

**Comment by Happypig375** [comment]
64th commit: Reworked the save/load LaTeX buttons in Example to simply modify an backend file; introduced a new StrokeCap property to SkiaMathPainter and FormsMathView; in the process of porting MakeAccents, MakeOverline and MakeUnderline of Typesetter (the cause of exception in \hat was due to these not being implemented)

**Comment by Happypig375** [comment]
@charlesroddie 
I think I found the LaTeX command for inline vs display style maths.
`\textstyle{\int^6_5}\displaystyle{\int^6_5}`
![image](https://user-images.githubusercontent.com/19922066/41509187-d738c064-7282-11e8-8e62-e28a967c9c30.png)

**Comment by Happypig375** [comment]
For some reason limits are not working with inline mode maths. Added to todo list.
`\textstyle{\int\limits^6_5}\displaystyle{\int\limits^6_5}`
![image](https://user-images.githubusercontent.com/19922066/41509242-75fd8f72-7283-11e8-9495-f611272ed971.png)

**Comment by charlesroddie** [comment]
Renamed thread to SkiaSharp renderer. This will work on any .Net platform supported by SkiaSharp, whether via Xamarin.Forms or not.

Any cool stuff that is Forms-specific we can discuss separately.

I don't think we need a logo; it's surprisingly hard to make a good one.

Thanks again @Happypig375 .

**Comment by charlesroddie** [comment]
> @prepare 'gesture input' => 'math glyph' => math equation! I'm waiting for that :)

Really hard to do. MyScript and WIRIS own the best tech for this as far as I can tell. Unfortunately neither has anything cross-platform except via webviews and the cloud.

**Comment by charlesroddie** [comment]
> Well, I guess that Xamarin.Forms will be the major market here because not many people use SkiaSharp without Xamarin.Forms 🤔

Forms is the most popular .Net approach to cross-platform development, but people still write single-platform code, e.g. desktop WPF, or separate Xamarin.iOS and Xamarin.Android. It's important that the main renderer just has a .net standard dependency without a Forms dependency - which I think is the case at the moment, isn't it?

> It's because if they allow it to be available offline, then people will decompile it and they would lose money due to leaked technology 😛

MyScript is available offline but with separate components per platform so cross-platform integration is hard.

**Comment by Happypig375** [comment]
65th commit: iosMath examples now can be seen in More Examples page!
![iosMath Examples](https://user-images.githubusercontent.com/19922066/41530289-588445f4-7322-11e8-8d88-8849cc4337f1.jpeg)

**Comment by Happypig375** [comment]
66th commit: Badges in README

**Comment by charlesroddie** [comment]
I get an error on loading the solution in the SkiaSharp branch. "... CSharpMath\Obj\project.assets.json" doesn't have a target for '.NETStandard, Version=v1.3'. I can see the code but can't run anything. @foggyfinder can you try this and see if you get the same problem?

**Comment by FoggyFinder** [comment]
> @FoggyFinder can you try this and see if you get the same problem?

@charlesroddie try remove obj and bin folders and rebuild project

**Comment by prepare** [comment]
@Happypig375 , 

I'm not sure that this position is correct or not.

Could you provide reference images?


![cap_pos](https://user-images.githubusercontent.com/7447159/41561857-349d4ba6-7375-11e8-8a7d-97affce348d1.png)

**Comment by Happypig375** [comment]
@prepare Yup, that is definitely a bug.
That is the wedge symbol, repredenting a logical conjunction (AND operation). It shiuld be typesetted in between the variables, not above.

**Comment by Happypig375** [comment]
67th commit: Emailed @verybadcat about bugfixing

**Comment by Happypig375** [comment]
68th commit: Reworking icon; in progess

**Comment by Happypig375** [comment]
69th commit: Second iteration of the CSharpMath icon, awaiting @verybadcat bugfixes
![image](https://user-images.githubusercontent.com/19922066/41608612-7158c092-741b-11e8-9b31-7edc828f741c.png)

**Comment by Happypig375** [comment]
70th commit: TeX typesetted with the new \raisebox command added in this commit
Also added: \kern, \mkern, \hskip, \mskip commands
To add: \TeX

(This is a large commit 😛)

`123\raisebox{16mu}{456}789 \\ \text{T\kern-.1667em\raisebox{-.5ex}{E}\kern-.125emX}`
![image](https://user-images.githubusercontent.com/19922066/41668186-5af67116-74e1-11e8-87e7-ec47d4e7a0ea.png)

**Comment by Happypig375** [comment]
71th commit: A couple bugfixes, fixed @prepare's comment's bug

**Comment by Happypig375** [comment]
72th commit: Staticified almost all FrontEnd-implementing classes to reduce memory, GC pressure and increase performance in speed

**Comment by Happypig375** [comment]
73rd commit: Test buildable again

**Comment by Happypig375** [comment]
74th commit: Started implementing feature 'Text and Maths'

**Comment by Happypig375** [comment]
75th commit: I can't believe it! Fixing a wedge display also fixes stuff like this! 😮
Compare (Look at Matrix3):

Before|After
-|-
![Before](https://user-images.githubusercontent.com/19922066/41811121-104189be-773c-11e8-9f83-5376a605dd40.png)
|![After](https://user-images.githubusercontent.com/19922066/41811075-2e512bb8-773b-11e8-8d7c-32770756eadc.png)

**Comment by Happypig375** [comment]
76th commit: My fix for 1 \\\\ { 2 \\\\ 3 } for @verybadcat's reference
77th commit: Introduction of BiDictionary to replace DictionaryHelpers; fixed accents, fixed overlines, fixed underlines, iosMath examples now should be all bug-free, iosMath examples magnified to be more readable

**Comment by Happypig375** [comment]
78th commit: In process of fixing x{\\scriptstyle y}z

**Comment by Happypig375** [comment]
79th commit: Fixed limits in text style, \sin, \cos etc are now non-limitable, also added \iint, \iiint etc, removed unused NuGet packages, added new CSharpMath.Utils.Release to prepare for a NuGet spec editor
(All of the projects got modified - what a great view to see)
`\textstyle{\int\limits^6_5}\displaystyle{\int\limits^6_5}\textstyle{\int\nolimits^6_5}\displaystyle{\int\nolimits^6_5}`
![image](https://user-images.githubusercontent.com/19922066/41845883-9b6dd774-78a7-11e8-86a4-492676863fe5.png)

@prepare How's the Typography.TextBreak port going?

**Comment by charlesroddie** [comment]
@Happypig375 I get the following build errors, similarly to the last time I tried. Fresh clone.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\charl\source\repos\csharpmath\CSharpMath.Forms.Example\CSharpMath.Forms.Example\bin\Debug\netstandard2.0\CSharpMath.Forms.Example.dll' could not be found	CSharpMath.Forms.Example.UWP	C:\Users\charl\source\repos\csharpmath\CSharpMath.Forms.Example\CSharpMath.Forms.Example.UWP\CSC	1	Active
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.OpenFont\Typography.OpenFont.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Utils\CSharpMath.Utils.csproj" at (19,3), due to the file not existing.	CSharpMath.Utils	C:\Users\charl\source\repos\csharpmath\Typography\Typography.OpenFont\Typography.OpenFont.projitems	19	
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.GlyphLayout\Typography.GlyphLayout.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Utils\CSharpMath.Utils.csproj" at (20,3), due to the file not existing.	CSharpMath.Utils	C:\Users\charl\source\repos\csharpmath\Typography\Typography.GlyphLayout\Typography.GlyphLayout.projitems	20	
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.OpenFont\Typography.OpenFont.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Rendering\CSharpMath.~Rendering~.csproj" at (51,3), due to the file not existing.	CSharpMath.~Rendering~	C:\Users\charl\source\repos\csharpmath\Typography\Typography.OpenFont\Typography.OpenFont.projitems	51	
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.GlyphLayout\Typography.GlyphLayout.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Rendering\CSharpMath.~Rendering~.csproj" at (52,3), due to the file not existing.	CSharpMath.~Rendering~	C:\Users\charl\source\repos\csharpmath\Typography\Typography.GlyphLayout\Typography.GlyphLayout.projitems	52	
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\PixelFarm.NetStandard\PixelFarm.Triangulation\PixelFarm.Triangulation.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Rendering\CSharpMath.~Rendering~.csproj" at (53,3), due to the file not existing.	CSharpMath.~Rendering~	C:\Users\charl\source\repos\csharpmath\Typography\PixelFarm.NetStandard\PixelFarm.Triangulation\PixelFarm.Triangulation.projitems	53	
Error		Project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.Contours\Typography.Contours.projitems" was not imported by "C:\Users\charl\source\repos\csharpmath\CSharpMath.Rendering\CSharpMath.~Rendering~.csproj" at (54,3), due to the file not existing.	CSharpMath.~Rendering~	C:\Users\charl\source\repos\csharpmath\Typography\Typography.Contours\Typography.Contours.projitems	54	
Error	MSB4019	The imported project "C:\Users\charl\source\repos\csharpmath\Typography\Typography.OpenFont\Typography.OpenFont.projitems" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	CSharpMath.~Rendering~	C:\Users\charl\source\repos\csharpmath\CSharpMath.Rendering\CSharpMath.~Rendering~.csproj	51	
```

**Comment by charlesroddie** [comment]
It would be nice to clean up the API a bit. Current issues and suggestions (although I could easily be on the wrong track as I can't build the project):

- MathPainter seems to be in the SkiaSharp namespace but that is for SkiaSharp itself. Suggest CSharpMath.SkiaSharp.
- CSharpMath.SkiaSharp should contain everything needed to render LaTeX to an SKSurface. There shouldn't be a need to open CSharpMath.Rendering or Typography.OpenFont.

**Comment by Happypig375** [comment]
@charlesroddie
You didn't clone with submodules, did you? The error means that the Typography project is not found. I guess not a lot of people understand git submodules.

Again, please check the Recurse Submodules box in Visual Studio. If that is not working, please go ahead and download git and use Git Bash to clone with the command given above after navigating to the relevant folder with `cd <directory>`.

As for the purpose of CSharpMath.Rendering, it is cross-platform and any graphics framework or platform can be plugged in. (For example, Unity). The CSharpMath core project has a similar philosophy.

The CSharpMath.SkiaSharp project is a minimal layer of glue between SkiaSharp and CSharpMath.Rendering. Its primary type is `CSharpMath.SkiaSharp.SkiaMathPainter`, which inherits `CSharpMath. Rendering.MathPainter` (as shown in documentation), and its primary method is `Draw(SKCanvas)`.

**Comment by Happypig375** [comment]
80th commit: NuGet spec editor in progress

**Comment by charlesroddie** [comment]
Thanks @Happypig375 . I did check recursively clone, but it needed a manual recursive clone after switching branches.

**Comment by Happypig375** [comment]
81st commit: NuGet spec editor!
![image](https://user-images.githubusercontent.com/19922066/41987697-80348ad6-7a6c-11e8-9684-f3ab861a3bb0.png)

**Comment by Happypig375** [comment]
82nd commit: Release mode testing, 3rd iteration of CSharpMath icon (frozen for 0.1.0), Adding the 3rd iteration icon to Forms Example projects
![icon_transparent](https://user-images.githubusercontent.com/19922066/42028076-dec543a6-7afd-11e8-9bd9-ff126a50d036.png)

**Comment by Happypig375** [comment]
83rd commit: Publishing 0.1.0-pre1

**Comment by Happypig375** [comment]
0.1.0-pre1 has been published!
Goodbye first issue, you will be remembered 😢
Well, progress report will continue at #12.


P.S. A long issue like this one takes a while to load on my phone, so I guess it is really appropriate to start a new thread. 💭
