### ISSUE TITLE
Forms MathView should update when binded latex property value is changed

### ISSUE THREAD

**Issue by BartoszBojda** [verybadcat/CSharpMath#106]
I'm making app in which math formula is changing dynamically inside the page, but displayed math view is not changing, I have to restart page which is not convinient in my problem.

**Comment by Happypig375** [comment]
Our example project does this just fine. Please attach a reproduction project.

**Comment by BartoszBojda** [comment]
Ok, I found in example project that solution was to call InvalidateSurface from MathView.At first I thought that it would be working by itself and after that I couldn't find other way to do it. Thank you very much for help.
