### ISSUE TITLE
Math Input (MathEditor port)

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#11]
Just as CSharpMath started as a port of iosMath, MathEditor, which builds on iosMath, could be ported to add editing support to CSharpMath.

@verybadcat can you keep us updated about your thoughts on doing this port? Thanks!

**Comment by Happypig375** [comment]
I'm targeting this for 0.2.0 for now.

**Comment by Happypig375** [comment]
I'm afraid that this will take longer than expected. Can you please allow a few more days?

**Comment by Happypig375** [comment]
0.2.0-alpha has been put on NuGet.
Touch response (navigation) is still being worked on.
The main property is `CSharpMath.Forms.EditableMathView.Default`.

**Comment by charlesroddie** [comment]
Great! Is this ready to test? We are a bit overloaded here for the next few days but can test soon.

**Comment by Happypig375** [comment]
0.2.0-alpha2 is ready!
Still bugfixes to go though.

**Comment by Happypig375** [comment]
0.2.0-alpha3 brings an editor which left/right buttons are usable.
Please test~

![ezgif-5-168f0fc3866b](https://user-images.githubusercontent.com/19922066/48964953-2d88e000-efee-11e8-82af-408a1715ea9a.gif)

**Comment by Happypig375** [comment]
I intend to wrap this up very soon. Touch insertion will be pushed to the F# version. Is there an API shape that you would like to be seen?

**Comment by charlesroddie** [comment]
Gif looks good @Happypig375 . Could we have a normal cursor?

This is the API that I would like:

- A view with Skiasharp dependency only (not Forms).
- Properties and instance methods on the input View for inserts/commands.
- A property for getting latex (perhaps to be replaced with a structural version in the future F# version).
- A method for setting the cursor position based on a coordinate (understood that this is pushed to the F# version).

Inserts/commands needed:
- Left, right, up, down, backspace, clear
- left bracket "(", right bracket ")", 0-9, decimal place, divide, times (cdot), minus, plus
- Characters a-z, A-Z, greek
- Functions including sin, cos, tan ,sin^-1, cos^-1, tan^-1, power, sqrt, nth root, modulus ("| |"), sinh, cosh, tanh, exp ("e^"), ln, log, "!".

Some intelligence will be needed eventually about combining inputs. E.g. if the user types "s" then "i" then "n" it should get combined into the sin function. (To accomodate keyboard usage.) MathQuill is a good reference for good behavior.

Does this conform to what you had in mind?

**Comment by Happypig375** [comment]
Usage as of 0.2.0-beta1:
1. Having a custom keyboard:
```cs
//from XAML
SkiaSharp.Views.Forms.SKCanvasView canvasView = ...;
Xamarin.Forms.Button button = ...;

var painter = new CSharpMath.SkiaSharp.MathPainter
{ /*set all properties aside from LocalTypefaces, FontSize, LineStyle,
    MathList, LaTeX and Source (these are ignored)*/ };
var keyboard = new CSharpMath.Rendering.MathKeyboard(/*optional fontSize*/)
{ /*set Fonts, LineStyle and InsertionIndex here*/ };
button.Pressed += (sender, e) => keyboard.KeyPress(CSharpMath.Editor.MathKeyboardInput.SmallX /*or any key*/);
keyboard.RedrawRequested += (sender, e) => canvasView.InvalidateSurface();
canvasView.PaintSurface += (sender, e) => {
  e.Surface.Canvas.Clear();
  //for any DrawDisplay overload, arguments after canvas are the same as Draw
  CSharpMath.SkiaSharp.MathPainter.DrawDisplay(painter, keyboard.Display, e.Surface.Canvas);
  keyboard.DrawCaret(
    new CSharpMath.SkiaSharp.SkiaCanvas(e.Surface.Canvas, SkiaSharp.SKStrokeCap.Butt, false),
    CSharpMath.Rendering.CaretShape.IBeam);
};
```
![screen](https://user-images.githubusercontent.com/19922066/50734289-f5251600-11d7-11e9-9d48-01dba5b3c2cc.gif)
2. Using the default keyboard:
```cs
//from XAML
SkiaSharp.Views.Forms.SKCanvasView canvasView = ...;
CSharpMath.Forms.MathKeyboard keyboard = ...;

var painter = new CSharpMath.SkiaSharp.MathPainter
{ /*set all properties aside from LocalTypefaces, FontSize, LineStyle,
    MathList, LaTeX and Source (these are ignored)*/ };
keyboard.RedrawRequested += (sender, e) => canvasView.InvalidateSurface();
canvasView.PaintSurface += (sender, e) => {
  e.Surface.Canvas.Clear();
  //for any DrawDisplay overload, arguments after canvas are the same as Draw
  CSharpMath.SkiaSharp.MathPainter.DrawDisplay(painter, keyboard.Display, e.Surface.Canvas);
  keyboard.DrawCaret(e.Surface.Canvas, CSharpMath.Rendering.CaretShape.IBeam);
};
```
![screen](https://user-images.githubusercontent.com/19922066/50734435-2272c380-11da-11e9-9781-c1cf3072cb79.gif)

**Comment by Happypig375** [comment]
To anyone following this thread, please cast a vote on https://github.com/verybadcat/CSharpMath/issues/4 - I'm starting the F# project really soon.

**Comment by Happypig375** [comment]
@charlesroddie Any suggestions for improvement? I intend this to be the final API of 0.2.0.

**Comment by charlesroddie** [comment]
Great. We'll take a look today.

**Comment by charlesroddie** [comment]
The `CSharpMath.Editor.MathKeyboardInput` enum is clunky to use with all the separate characters. It suggests that consuming code would need to write out all the mapping between a char and the MathKeyboardInput enum.
Perhaps just add a `FromChar` method? This would just be one line `FromChar c = EnumOfValue(int c)` but it would make it clearer how to use the keyboard.
In the future F# library it would have a DU where single character a-z, α-ω... input is its own case.

**Comment by charlesroddie** [comment]
Otherwise the API looks very usable.

**Comment by charlesroddie** [comment]
Accepting physical keyboard input on Xamarin.Forms depends on https://github.com/xamarin/Xamarin.Forms/issues/3444

**Comment by charlesroddie** [comment]
To respond to touch/mouseclicks, we need a method to set the current edit/cursor location based on position. This should be doable but any idea how hard it will be @Happypig375 ?

**Comment by Happypig375** [comment]
There exists such a method in `MathKeyboard` but its result is awfully wrong. I plan to rewrite it in MathDisplay.NET.

**Comment by Happypig375** [comment]
For the FromChar method, currently just using `keyboard.KeyPress((CSharpMath.Editor.MathKeyboardInput)'x')` works just fine, because the enum values are specifically defined as the Unicode codepoints of the characters.

**Comment by Happypig375** [comment]
@charlesroddie All issues seem to be resolved. Any more issues?

**Comment by Happypig375** [comment]
If there are no more issues, I'll be releasing 0.2.0 the next few days.

**Comment by Happypig375** [comment]
Implemented, closing.
