### ISSUE TITLE
Math LatexView doesn't show on physical iOS Device 

### ISSUE THREAD

**Issue by ImadAbuDev** [verybadcat/CSharpMath#110]
Hi,
I am working on a crossplattform application. On android phones and simulators the latex view shows up and everything works fine. Also if I use I Phone Simulator the view shows up with the correct numbers and equations. But if I load the application on a physical I Phone device all latex views are like empty and they don't show any texts or anything. Normal buttons or labels are working as usual.
This seems to happen to me only on an physical iOS device. 
I used the free provisoring which is described here https://docs.microsoft.com/de-de/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=windows
to deploy it on my I Phone maybe that is the problem cause I don't have developer license yet.

I would appreciate any help. I love this latexmath view and want it to be running without fails on any Phone Thank you for your work.

**Comment by Happypig375** [comment]
Unfortunately I don't own physical iPhones so I cannot debug this 😢

**Comment by Happypig375** [comment]
Assuming you're using CSharpMath.Forms, this may be a SkiaSharp bug.

**Comment by Happypig375** [comment]
Free provisioning is not related to this issue. As you can put your app on an iPhone, this already indicates that it works. Please attach a reproduction solution so that I can search for possible causes.

**Comment by ImadAbuDev** [comment]
I don't know what you mean by reproduction solution but here is my code https://we.tl/t-IaNyLZ1Ka7

**Comment by Happypig375** [comment]
Try calling `InvalidSurface()` on the `MathView`?

**Comment by ImadAbuDev** [comment]
will try it thanks. One other question if you don't mind how can I use a mathview on a button? Is this possible?

**Comment by Happypig375** [comment]
@ImadAbuDev What a coincidence! The latest commit 713e480 just added a MathButton - you can copy its source for now until a new release arrives.

**Comment by Happypig375** [comment]
The `DrawAsStream` extension method is defined in https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath.SkiaSharp/Extensions.cs

**Comment by ImadAbuDev** [comment]
@Happypig375  that's great! what exactly do I have to copy and where ? since I can't change the NuGet Package content itself

**Comment by Happypig375** [comment]
You can copy the code directly to your app, preferably with a different namespace so that class names will not clash when you update.

**Comment by DevImad17** [comment]
Ok will try it thanks when to expect new release?

**Comment by ImadAbuDev** [comment]
Ok will try thanks when to expect new release?

**Comment by Happypig375** [comment]
I'll publish a new prerelease `0.4.0-beta` in the next few days. Did the provided solution work?

**Comment by Happypig375** [comment]
@ImadAbuDev Did the solution work for you?

**Comment by Happypig375** [comment]
If there is no response, I will consider this question successfully answered.

**Comment by ImadAbuDev** [comment]
Sorry for late response haven't tried it yet since I have no I Phone in my Home office (only android) will check when I have access to one. For the button I tried to copy the code but did't work for me properly  I will just wait for new release :)

**Comment by Happypig375** [comment]
As of `0.4.0-beta`, calling `InvalidateSurface()` will be done automatically. Please check if this is fixed.

**Comment by ImadAbuDev** [comment]
Where can I update to beta version  in Visual studio?

**Comment by FoggyFinder** [comment]
> Where can I update to beta version in Visual studio?

https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages

**Comment by Happypig375** [comment]
@ImadAbuDev Problem solved?

**Comment by ImadAbuDev** [comment]
yes thanks

**Comment by Happypig375** [comment]
Alright
