### ISSUE TITLE
Punctuation should stick to inline maths

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#113]
TextPainter correctly deals with punctuation after words, but punctuation after inline maths gets separated from the maths.

E.g. "... $x$."

![image](https://user-images.githubusercontent.com/19760720/79401211-65484d00-7f80-11ea-8731-630a0ac70ed8.png)

In this example the "." should not separate from the "$x$" and they should be grouped together for line-breaking purposes.

**Comment by Happypig375** [comment]
What about display maths? Should it also be considered?

**Comment by charlesroddie** [comment]
No because display maths is rendered on a separate line:
```
Famous equations include $$e^{i\pi}+1=0$$, $$e=mc^2$$, and $$c^2=a^2+b^2$$.
```
<img src="https://user-images.githubusercontent.com/19760720/82696193-71e65200-9c5e-11ea-872a-abbf2f84aa64.png" width="200">
