### ISSUE TITLE
Add helpful methods to have more control over blinking caret.

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#115]
**Is your feature request related to a problem? Please describe.**
Internal timer creates excessive load to the system when there are many editors on a single page.
That in worst cases can leads to [#4667](https://github.com/xamarin/xamarin-android/issues/4667)

**Describe the solution you'd like**
Add some methods so one could easily turn on/off timer.

**Describe alternatives you've considered**
None

**Difficulty: How difficult would it be? (Trivial, Very Easy, Easy, Moderate, Hard, Very Hard, Tedious, Backbreaking)**
Depends on approach. I suppose trivial / easy for the straightforward case.

**Comment by Happypig375** [comment]
I'm thinking of special-casing so that the timer will not be created when `blinkMilliseconds` is `System.Threading.Timeout.Infinite` (`-1`).

**Comment by charlesroddie** [comment]
I was also thinking of along those lines with a nullable `blinkMilliseconds`.

But I think @FoggyFinder 's idea is better as having a blinking caret is a good feature. It just needs to minimize the timers. So turning them off and on is a better idea. It may be as simple as exposing the blinkTimer.Start() and .Stop() methods.
