### ISSUE TITLE
Standardize formatting?

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#118]
Currently there is an .editorconfig file which gives non-standard formatting like
```
indent_size = 2
...
# Deviates from .NET Formatting Conventions
```

@Happypig375 can we move to standard .Net formatting conventions? By changing the settings or by deleting .editorconfig?

**Comment by Happypig375** [comment]
These formats were set up by @verybadcat and to be honest I like it as it greatly reduces whitespace on the left of the code. Visual Studio already provides indentation lines so visual differentiation is not that big of a deal.
![image](https://user-images.githubusercontent.com/19922066/82889298-1f1dda80-9f7d-11ea-98a4-fea184ce6c42.png)

**Comment by Happypig375** [comment]
I also like brace on the previous line as it can greatly reduce the number of "brace lines" that just clutter reading. Indentation already provides such information.

**Comment by charlesroddie** [comment]
OK. The code is hard to struture visually and looks rather dense. But since you like it and are the main maintainer we can close this.
