### ISSUE TITLE
CSharpMath 0.1.0-pre1, 0.1.0-pre2, 0.1.0-pre3 and 0.1.0-pre4 have been released!

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#12]
0.1.0-pre1 Announcement:

With the 0.1.0 SkiaSharp update, beautiful math rendering in SkiaSharp and Xamarin.Forms is now possible.
Currently in prerelease state, it is [available for download](https://www.nuget.org/packages?q=CSharpMath) for testing. Test all the packages as hard as you can! You can contribute to bug-smashing.
The master branch has been rebased onto SkiaSharp, which is planned to be deleted.

Please report any issues with this prerelease inside this issue!

## Known issues
- [ ] `1 \\ { 2 \\ 3 }`'s spacing between 1 and 2 is weird
![image](https://user-images.githubusercontent.com/19922066/42049804-b52f8aba-7b39-11e8-8ae0-261fe49d7950.png)
- [x] Too few tags for the packages (suggested: formula tex render)
- [ ] CSharpMath.Text (#6) is not yet implemented
- [ ] No way to limit scrolling to horizontal only or vertical only
- [ ] CSharpMath.Forms.Example.UWP is not buildable with .NET Native Toolchain enabled
- [ ] Loading times of CSharpMath.Forms.Android.Example is still very slow in Release mode
- [x] Instructions for cloning with submodules is incomplete. ~~Suggest adding a custom analyzer.~~ (Note: the Roslyn Analyzer API was not deemed suitable, so a conditional file with #errors was used instead.)
- [ ] Pinching a FormsMathView has been removed due to SkiaSharp API limitations
- [ ] No Changelog for now (will be written in some future prerelease)
- [ ] Documentation is unfinished on both NuGet and GitHub wiki
- [ ] Unit tests are missing in general
- [ ] Release procedure is not documented
And finally,
- [ ] Promotion of CSharpMath not yet done

#1, #2, #3 and #10 will be merged into here.

Note: Active development will cease until 10th July due to travelling to mainland China. Hope to see you then!

**Comment by Happypig375** [comment]
Before | After 
--------|-------
![Before](https://user-images.githubusercontent.com/19922066/42050603-fcfd4fce-7b3b-11e8-8c7a-215efc271876.png)|![After](https://user-images.githubusercontent.com/19922066/42050571-ed2921cc-7b3b-11e8-81cf-ce42c5ca9e64.png)

Much better with the icon 😃

**Comment by charlesroddie** [comment]
`'Could not load file or assembly 'Typography.OpenFont, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'`

**Comment by charlesroddie** [comment]
Also notice that SkiaMathPainter takes an SKSize (width and height) and an optional fontsize. I don't fully understand that. What role do width and height play? Are they for resizing? Surely based on a fontsize, the resulting SKSize is given?

**Comment by Happypig375** [comment]
@charlesroddie
- [ ] It seems to be loading a Typography DLL... I did not encounter this exception while testing the examples. The workaround is building from source right now.

- [ ] The role for width and height during construction of SkiaMathPainter is to calculate the appropriate alignments and padding for drawing. Aside from providing in the constructor, the bounds of drawing should also be set to the Bounds property before drawing; a better way would have been required parameters for the Draw method.

**Comment by charlesroddie** [comment]
## API Comments

### Sizing

A `SkiaMathPainter` should require a fontsize (which can have a default if not given) and a source to construct. It shouldn't require any other measurements.

An instance of `SkiaMathPainter` should have a `Measure:unit -> SKSize` property. It should also have a `Draw:SKCanvas*SKPoint->unit` property. The `SKPoint` is the upper left coordinate, just like `canvas.DrawText`.

(Alternatively, a `SkiaMathPainter` doesn't require a font size, and should have `Measure(fontsize)` and `Draw(canvas, point, fontsize)` properties.)

You can easily make margins and centering as needed out of Measure and Draw. The same `SkiaMathPainter` can draw at different places, as the canvas changes size, and into diferent canvases if needed.

### Sources

There are a lot of overloads in the `SkiaMathPainter` and `MathSource` w.r.t. sources, and invalid combinations of properties result.

For example you can specify a `MathSource` based on an `IMathList` and then get it's `LaTeX`, and I think that will fail as the `LaTeX` is not defined. I believe your idea for Source is to bypass LaTeX - a good idea in theory - but then there should not be LaTeX properties and definitly not properties with getters.

Suggestion: remove the potentially invalid getters, and also remove the indrect overloads.

A `SkiaMathPainter` depends most directly on something. Maybe it's an `Atom`. Let the `SkiaMathPainter` require that input as its source, and remove the other overloads. We could end up with:

```fsharp
let atom = Atom.FromTeX(tex)
let painter = SkiaMathPainter(Atom = atom, FontSize = 12.)
```

We could then have more constructors for `Atom`, e.g. `Atom.FromMathML(...)` if someone wants to implement that in future. Or we can define atoms directly to bypass parsing. This example (different string types) suggests different methods rather than different overloads here.

The `SkiaMathPainter` constructor then does not need a TeX overload getter or setter.

Actually I think the `Atom` here should be required in the `SkiaMathPainter` constructor and not settable. Since any change is effectively recreating the object anyway, there are no effiency gains in letting this property be settable.

(I am using `Atom` here as I don't yet know what a `Source` is or how it's different from an `Atom`.)

**Comment by Happypig375** [comment]
@charlesroddie
Removing the width and height constructor arguments, the Bounds property, and replacing them with the availableWidth and availableHeight parameters for the Draw method is planned for pre2.

I am not requiring the point of drawing to be supplied directly because in practical usage, the math painter is typically used for views. (Like your MathView that is derived from SKGLView). Ideally, the available size parameters should be directly fed to from the platform-given arguments on draw. (Now, different canvases can be drawn onto by the same math painter.) If the drawing point was to be supplied directly, the alignments of the content would need to be calculated externally, which won't be useful. Maybe I can even use the LocalClipBounds property of SKCanvas directly instead of these parameters.

Regarding the Measure property, it is provided currently by the name of DrawSize.

Getting LaTeX from a MathSource constructed with an IMathList **is valid.** Try it yourself.

Oh yes,
- [ ] Support raisebox atom to LaTeX (forgot to add this)

The intention of having a MathSource is to support translations between different math languages. For each language, only two translators are needed: language->MathList and MathList->language. This way, we can get convert e.g. MathML to LaTeX without the use of an actual painter.

- [ ] add above to documentation

All of the content properties (e.g. LaTeX) of math painters are just convenience properties for the MathSource.

If you do want to avoid the MathSource structure, use `CSharpMath.Atoms.MathLists.BuildResultFromString`. An Atom represents a LaTeX command, and a MathList represents a container of LaTeX commands. A MathList is inherently not an Atom as noted in the XML Documentation of IMathList. As LaTeX usually contain more than one atom, a MathList is used in here. A MathSource represents not just any one atom or any series of atoms, but the document that contains ALL the commands.

- [ ] A new wiki page for above

A math painter's content is mutable because there is no need to reassign every other property just for a change in its content.

**Comment by charlesroddie** [comment]
> If the drawing point was to be supplied directly, the alignments of the content would need to be calculated externally.

There is no need to align content in the main draw method, and that is why specifying available heights and widths should not be in there, but specifying a point should. As discussed above, it would be standard to specify the top left point. You can take the SkiaSharp drawing methods as a guide to a good API here.

You are welcome to add a convenience method DrawAligned(rect:SKRect, horizontalAlignment, verticalAlignment), or overload Draw with this, but it should not be the main Draw method.

> The intention of having a MathSource is to support translations between different math languages. For each language, only two translators are needed: language->MathList and MathList->language. This way, we can get convert e.g. MathML to LaTeX without the use of an actual painter.

That sounds fine. From what you are saying there is no difference in data between a MathSource and a MathList. So I would not have two separate names for these.

**Comment by Happypig375** [comment]
0.1.0-pre2 would have been released if not the two-factor authentication blocking myself from signing into NuGet.
To anyone viewing this, here are the packages to try out:
https://github.com/verybadcat/CSharpMath/releases/tag/v0.1.0-pre2

**Comment by charlesroddie** [comment]
Great. Did you work out how to fix the missing typography dlls?

**Comment by Happypig375** [comment]
0.1.0-pre2 is now out for download on NuGet.

Major changed since 0.1.0-pre1:
- Reworked Draw methods
- Removed bounds constructor parameters and the Bounds property
- Renamed LayoutBounds property to Measure
- Should-be-fixed exception of Typography DLL not being found (please verify)
- Plus change of the IPainter interface

**Comment by charlesroddie** [comment]
Yes the Typography DLL issue is fixed in 0.1.0-pre2.

Thanks for redoing the api. A SkiaMathPainter's .Measure property is a `Nullable<System.Drawing.RectangleF>`. 1. Surely you should always be able to get a measure, so it shouldn't be nullable. 2. RectangleF has left,right,top,bottom. Isn't a measure height and width? `SKSize` and `SKPoint` would work well for the Measure property and Draw method.

Just started testing. With the code:
```fsharp
type MathView(tex) =
    inherit SkiaSharp.Views.Forms.SKGLView(HeightRequest = 200.)
    let mathpainter = CSharpMath.SkiaSharp.SkiaMathPainter( AntiAlias = true, LaTeX = tex )
    override t.OnPaintSurface(e : SkiaSharp.Views.Forms.SKPaintGLSurfaceEventArgs) =
        mathpainter.Draw(e.Surface.Canvas, System.Drawing.PointF(0.f,0.f))
```
I get an unhandled exception with no debug information. Without `System.Drawing.PointF(0.f,0.f)` it renders OK.

**Comment by Happypig375** [comment]
- [ ] Add following to documentation

The Measure property returns:
- null if MathList is null or LaTeX contains an error
- a rectangle with x coordinate zero, y coordinate the descent of the laid out content (so that you can know how much the starting point is below the baseline), width and height same as width and height of content.
(Therefore, you are meant to look at Y, width and height instead of left, right, top and bottom.)

The Draw(SKCanvas, PointF) overload always throws NotImplementedException that was used to test private vs public method resolution. I forgot to change it back to using an actual implementation and will do it in the next prerelease. Use the Draw(SKCanvas, float, float) overload that takes x and y coordinates as separate parameters for now.

**Comment by charlesroddie** [comment]
There is a bug in the y coordinate. `Draw(canvas,x,y)` draws the latex starting from (x,y+canvasHeight) instead of (x,y). So `Draw(canvas,0.f,0.f)` displays at the bottom left of the canvas, when it should be the top left.

Otherwise the SkiaMathPainter method is consistent with standard Skia text rendering. (I was wrong about standard text coordinates before. The point specified is at the bottom left not the top left. That's OK and unrelated to the coordinate problem above.)

**Comment by charlesroddie** [comment]
Some of the underlying functions are 1. unreliable, and 2. not pure functions.
```fsharp
let mathpainter = CSharpMath.SkiaSharp.SkiaMathPainter(LaTeX = tex )
let measure = mathpainter.Measure.Value
let c = MathSource(tex).MathList.Count
```
Sometimes the measure looks right, and the display is right. And sometimes the measure is 0, and nothing displays. Somtimes MathLIst has 1 item, and sometimes 0, for the same TeX. It depends on where and when the SKGLView is instantiated, for unknown reasons.

Three problems:
1. The functions are not pure. (Presumably MathSource is the underlying offender.)
2. They are not correct.
3. There is no error message.

CSharp problems :) .

**Comment by charlesroddie** [comment]
(Deleted a comment - mistake while testing.)

**Comment by Happypig375** [comment]
@charlesroddie Is the deletion a mistake or the posting of comment a mistake? I can help repost it from email.

**Comment by charlesroddie** [comment]
> a rectangle with x coordinate zero, y coordinate the descent of the laid out content (so that you can know how much the starting point is below the baseline), width and height same as width and height of content.

I don't believe this is quite right. The descent is measure.Bottom not measure.Y. I find that the following displays very close:
```fsharp
let x,y = 100.f,100.f
let bounds = SKRect(x+measure.Left,y+measure.Top,x+measure.Right,y+measure.Bottom)
let canvas = e.Surface.Canvas
mathpainter.Draw(canvas,x,y - float32 self.Height)
canvas.DrawRect(bounds, new SKPaint(Color = SKColor(0uy,0uy,0uy), Style = SKPaintStyle.Stroke))
```

![image](https://user-images.githubusercontent.com/19760720/42732225-715cfbb8-8815-11e8-8caa-e43e852d9244.png)

The current behaviour here is good and what I would expect without documentation. `Draw(canvas,x,y)` draws into the rectangle `measure` translated by (x,y). (Aside from the y-coordinate bug above which requires subtracting `float32 self.Height` from the y coordinate of the draw method.)

**Comment by charlesroddie** [comment]
I am getting that mathPainter.Draw overwrites everything already on the canvas.

E.g.
```fsharp
mathPainter.Draw(canvas, 0.f, 0.f)
e.Surface.Canvas.DrawCircle(0.f,0.f,100.f,new SKPaint(Color = SKColor(255uy,0uy,0uy)))
```
Draws a red circle on a formula. But if the lines are swapped, the circle is not shown.

**Comment by charlesroddie** [comment]
@Happypig375 to summarize:
- Draw overload taking an SKPoint (minor)
- Draw y-coordinate incorrect offset
- Draw clearing everything currently drawn on the canvas

Can you confirm these?

Also do you have an idea of what is causing .Net Native incompatibilities? I get various warnings and an error. Possibly addressed in: https://github.com/dotnet/standard/issues/295 .
```
MCG : warning MCG0003: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface...
error : MCG0024: MCG0024:UnresolvableTypeReference Unresolvable type reference 'System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute' in 'Assembly(Name=System.Runtime.InteropServices, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)' found. Please check the references in your build system. A reference is either missing or an assembly is missing an expected type.
```

**Comment by Happypig375** [comment]
@charlesroddie 
Commit 949a2e48d5ef471ba4f61b403760ef5fafa77215:

- Draw(SKCanvas, SKPoint) overload added
- Fixed y-coordinate to start top-left instead of bottom-left

However, I am not noticing any clears by SkiaMathPainter.
```cs
      e.Surface.Canvas.DrawCircle(0f, 0f, 100f, new global::SkiaSharp.SKPaint { Color = new global::SkiaSharp.SKColor(255, 0, 0) });
      painter.Draw(e.Surface.Canvas, (float)x, (float)y);
      e.Surface.Canvas.DrawCircle(300f, 0f, 100f, new global::SkiaSharp.SKPaint { Color = new global::SkiaSharp.SKColor(255, 255, 0) });
```
![image](https://user-images.githubusercontent.com/19922066/42755517-118f12fe-892b-11e8-981c-96e26ff2991a.png)
Both circles before and after the Draw operation are there, suggesting that Draw does not clear the canvas.

**Comment by charlesroddie** [comment]
@foggyfinder can you investigate this please? We are getting that mathPainter.Draw clears the canvas (e.g. on line 693 of GraphVM.fs in the CSharpMath branch). But @Happypig375 doesn't get this. We may need to do a minimal repro.

**Comment by charlesroddie** [comment]
@Happypig375 What does [this line](https://github.com/verybadcat/CSharpMath/blob/8d4c39dac4ee9d86da5b39e06de0c2427b91676e/CSharpMath.Rendering/MathPainter.cs#L149) do?

(Also onlooking through the file: I assume that `CoordinatesFromBottomLeftInsteadOfTopLeft` is marked for removal/cleanup later?)

**Comment by Happypig375** [comment]
@charlesroddie
That line blends the entire canvas with the background colour given. It has no effect when BackgroundColour is transparent, which is the default. Did you set it?

**Comment by charlesroddie** [comment]
I am sure that line is causing the problem. `canvas.DrawColor(SKColor.Empty,SKBlendMode.Overlay)` turns the view gray which is exactly the problem I am getting with `mathPainter.Draw`.

Suggestion: Remove `BackgroundColor`, `canvas.DrawColor`, `FillColor()`. a MathPainter should not affect or interact with the canvas beyond the area into which it is drawing the LaTeX.

I think there is some cleanup to be done but we can do that after getting it working.

**Comment by charlesroddie** [comment]
@Happypig375 As soon as you can get pre3 nuget out without FillColor() we can release a beta incorporating CSharpMath. Thanks!

**Comment by Happypig375** [comment]
Now instead of having BackgroundColor, HighlightColor is now here.
It draws a filled rectangle behind the measured area to produce a "highlight effect" instead of using the weird method of FillColor.

[Included in 0.1.0-pre3.](https://github.com/verybadcat/CSharpMath/releases/tag/v0.1.0-pre3)

**Comment by charlesroddie** [comment]
Thanks a lot! Working well.

There is an issue with Measure now. `measure.Bottom` and `measure.Top` are switched and negated. So to get the true values you need `let top, bottom = -measure.Bottom, -measure.Top`. Width and Height are OK.

**Comment by Happypig375** [comment]
Does Y have the same issue?

**Comment by charlesroddie** [comment]
I forgot the definition of Y. How does Y relate to Bottom and Top?

**Comment by FoggyFinder** [comment]
@Happypig375 can you publish the new version, please?

**Comment by Happypig375** [comment]
0.1.0-pre4 released

**Comment by charlesroddie** [comment]
The .Net Native errors have changed to:
```
error : RHBIND : error RHB0011: Internal error: '!methodDesc->IsCanonicalMethod(CanonDefinitionTypeDiscoveryPolicy::AnyCanonLookup)' at 'f:\dd\ndp\rh\src\tools\rhbind\mdilmodule.cpp:12529'
error : ILT0005: 'C:\Users\Charles Roddie\.nuget\packages\runtime.win10-x64.microsoft.net.native.compiler\2.1.8\tools\x64\ilc\Tools\rhbind.exe @"C:\PROGRAMMING\GITHUB\CSharpMathMCVE\CsMathMcve\obj\x64\Release\ilc\intermediate\rhbindargs.CsMathMcve.rsp"' returned exit code 11
```
@Happypig375 do you think this is a Typography issue?

**Comment by Happypig375** [comment]
@charlesroddie 
Nope, I pinned it down to the System.Numerics.Vectors package. That package caused this error:
```
Error: NUTC1056: Internal Compiler Error: 0x8000ffff. Error encountered while compiling method 'instance System.Boolean System.Numerics.Plane.Equals(System.Numerics.Plane)'.
Error: ILT0005: 'C:\Users\user\.nuget\packages\microsoft.net.native.compiler\1.7.3\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Users\user\Source\Repos\NetNativeError\NetNativeError.UWP\obj\x86\Release\ilc\intermediate\MDIL\NetNativeError.UWP.rsp"' returned exit code 1
```

**Comment by Happypig375** [comment]
Welp, couldn't get the .NET Core source of System.Numerics.Vectors to compile either, even in Debug mode with the System.Numerics.Vectors.Performance.Tests project.
```
Error: Project 'C:\Users\user\Source\Repos\corefx\src\/System.Numerics.Vectors/ref/System.Numerics.Vectors.csproj' targets 'netcoreapp'. It cannot be referenced by a project that targets '_,Version=v0.0'.	System.Numerics.Vectors (src\System.Numerics.Vectors)	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1656	
```
Guess an issue will be filed at corefx, then.

**Comment by charlesroddie** [comment]
CoreRT is probably a better place to post.

**Comment by Happypig375** [comment]
Opened as https://github.com/dotnet/corert/issues/6131

**Comment by charlesroddie** [comment]
As far as I can tell from a quick search of the code, CSharpMath doesn't make significant use of System.Numerics.Vector, and Typography has it as an option `SYSTEM_NUMERICS_VECTOR` besides others.

**Comment by Happypig375** [comment]
I might just go with the Vector2 in Typography's source code. It is a polyfill for .NET Framework 2.0.

**Comment by Happypig375** [comment]
Merge into #15

**Comment by charlesroddie** [comment]
@Happypig375 By the way we released a beta using pre4 for [iPad](https://itunes.apple.com/us/app/mathspire/id1211653760) and [Windows 10](http://www.mathspire.com/GZqUWGMWvU/MathSpireWin10Demo.zip). Thanks for your work on this!
