### ISSUE TITLE
TextAlignment doesn't work

### ISSUE THREAD

**Issue by BenjaNapo** [verybadcat/CSharpMath#123]
### Bug Description
I'm using math:TextView for displaying math text and all works well, but when I try to display it with center alignment with the attribute TextAlignment="Center" it doesn't work. How can I fix it?

**Comment by Happypig375** [comment]
What code are you using and what is the result?

**Comment by Happypig375** [comment]
Will using `HorizontalOptions="FillAndExpand"` help? The `MathView` needs to occupy the entire space to align contents correctly.

**Comment by BenjaNapo** [comment]
> What code are you using and what is the result?
Code:
`<ContentPage.Content>
        <StackLayout Padding="20">
            <StackLayout
                x:Name="xStack"
                BindingContext="{Binding DomandaAttuale}"
                HorizontalOptions="CenterAndExpand"
                VerticalOptions="CenterAndExpand">
                <math:TextView LaTeX="Seleziona le affermazioni corrette sull'insieme dei numeri naturali $\mathbb{N}$." TextAlignment="Center" />
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>`
Result: 
![Screenshot_1591019608](https://user-images.githubusercontent.com/25958425/83415842-11a29d80-a420-11ea-9d92-3b136a5ee84b.png)

Thanks, for the fast answer ^^

**Comment by BenjaNapo** [comment]
> Will using `HorizontalOptions="FillAndExpand"` help? The `MathView` needs to occupy the entire space to align contents correctly.

I tried it, but doesn't even work

**Comment by Happypig375** [comment]
The text is actually centered. Are you looking for justification?

**Comment by BenjaNapo** [comment]
> The text is actually centered. Are you looking for justification?

Exactly, justification for Label it's called HorizontalTextAlignment

**Comment by Happypig375** [comment]
Oh, I know what you mean:
<p align="center">123456789<br/>this is what "centered" actually is</p>

**Comment by Happypig375** [comment]
Let me see if I can get this done today.

**Comment by BenjaNapo** [comment]
> Oh, I know what you mean:
> 
> 123456789
> this is what "centered" actually is

Idk if it is possible to do, but I thought that TextAlignment had that use

**Comment by Happypig375** [comment]
You can use
```
$$
\begin{gather}
\text{Centered}\\
\text{text}
\end{gather}
$$
```
as a workaround for now.

**Comment by BenjaNapo** [comment]
> You can use
> 
> ```
> $$
> \begin{gather}
> \text{Centered}\\
> \text{text}
> \end{gather}
> $$
> ```
> 
> as a workaround for now.

It seems working, but I need to get text from a binding... 

`<math:TextView LaTeX="{Binding Testo, Converter={StaticResource UrlDecoder}}" TextAlignment="Center" />`

So if you say that in a week/month it will work with an update I can wait

**Comment by Happypig375** [comment]
@BenjaNapo Take a look at #126 and see if that is what you need

**Comment by charlesroddie** [comment]
@Happypig375 can you translate this for me? What does this apply to? Is this xaml-specific, or Forms/Avalonia-specific?

**Comment by Happypig375** [comment]
@charlesroddie All uses of `TextPainter.Draw` with the `TextAlignment` overload.

**Comment by BenjaNapo** [comment]
> @BenjaNapo Take a look at #126 and see if that is what you need

I'm a little noob using github, how can I merge your changes with my project?

**Comment by Happypig375** [comment]
You can clone that branch locally, add the projects `CSharpMath`, `CSharpMath.Editor`, `CSharpMath.Rendering`, `CSharpMath.SkiaSharp`, `CSharpMath.Xaml` and `CSharpMath.Forms` to a test solution, and add a new project referencing `CSharpMath.Forms`.

**Comment by Happypig375** [comment]
@BenjaNapo The fix has been merged! You can try whether the fix is successful by [using the latest nightly packages](https://github.com/verybadcat/CSharpMath/packages).

**Comment by Happypig375** [comment]
Oops wrong issue sorry

**Comment by Happypig375** [comment]
Alright, the pull request has been merged for real this time. The commit is 810b47c314fc95ce7e1e3040deb6b3712147f32b

**Comment by Happypig375** [comment]
@BenjaNapo Added https://github.com/verybadcat/CSharpMath#opting-in-to-the-nightly-feed

**Comment by Happypig375** [comment]
Wait a moment. For some reason, the dependency version is out-of-date.
![image](https://user-images.githubusercontent.com/19922066/84369508-85eff480-ac09-11ea-84c6-7b4fdc79111b.png)

**Comment by Happypig375** [comment]
Above comment has been resolved

**Comment by BenjaNapo** [comment]
> Above comment has been resolved

I finally implemented it and it seems works well but not at all, I did as you said in the documentation, so I:
1. Created nuget.config and added relatives text with my credentials
2. Replaced in .csproj 
```
<PackageReference Include="CSharpMath" Version="0.4.2" />
<PackageReference Include="CSharpMath.Forms" Version="0.4.2" />
```
With
```
<PackageReference Include="CSharpMath" Version="0.4.2-ci-8cca3cc702ba45eb13e5bb1dff300a2ce37ded3d" />
<PackageReference Include="CSharpMath.Forms" Version="0.4.2-ci-8cca3cc702ba45eb13e5bb1dff300a2ce37ded3d" />
```
3. Went to the NuGet Manager and consolidated the version with mine
4. Tested it with these lines of code
```
<Grid Padding="20" VerticalOptions="StartAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="50*" />
                <RowDefinition Height="43*" />
                <RowDefinition Height="7*" />
            </Grid.RowDefinitions>
            <!--<Label
                HorizontalTextAlignment="Center"
                Text="{Binding DomandaAttuale.Testo, Converter={StaticResource UrlDecoder}}"
                VerticalOptions="Center" />-->

            <math:TextView
                Grid.Row="0"
                BackgroundColor="Red"
                FontSize="38"
                LaTeX="{Binding DomandaAttuale.Testo, Converter={StaticResource UrlDecoder}}"
                TextAlignment="Center" />
           ecc. ecc. ecc.
```

But that's the result:
![Screenshot_1592822716](https://user-images.githubusercontent.com/25958425/85279149-41c0e780-b486-11ea-8d81-5a2a8fdb1028.png)
As you can see there's some left padding that I didn't set

**Comment by Happypig375** [comment]
Hmmm. Seems that text is centered but the whole block is shifted to the right.
![image](https://user-images.githubusercontent.com/19922066/85280027-f58f9a80-b4b9-11ea-94bd-b59077e3e67b.png)

**Comment by BenjaNapo** [comment]
I found another bug, should I open a new issue? Or I wait the fix of this?

**Comment by Happypig375** [comment]
You can open issues to report bugs whenever you want. They are free to create.

**Comment by Happypig375** [comment]
@BenjaNapo This one should be fixed for good. Try the latest commit!

**Comment by BenjaNapo** [comment]
> @BenjaNapo This one should be fixed for good. Try the latest commit!

Perfect! Now I'll try and let you know
