### ISSUE TITLE
Universal Windows Platform support

### ISSUE THREAD

**Issue by yoshiask** [verybadcat/CSharpMath#125]
**What is this platform?**
The primary platform for modern Windows apps, which can run on all Windows 10 devices.

**Why should it be supported?**
Some developers don't want to deal with cross-platform frameworks like Uno or Xamarin.Forms. It would also allow easier porting of WPF (and to a lesser extent, WinForms) apps.

**Why should it not be supported?**
UWP is already available using Xamarin.Forms, and #121 would support it via the Uno Platform.

**Additional context**
I personally want to use this in my UWP project, and while it's already pretty easy, rendering to an SKCanvas manually doesn't have the advantages of being its own XAML control. For example, databinding isn't possible when rendering using a MathPainter in the code behind.

**Comment by Happypig375** [comment]
Platform Uno will _not_ be referenced when used in a UWP project.
https://github.com/verybadcat/CSharpMath/pull/121/files#diff-804e77684648c08794add964c24dabd1R12

**Comment by Happypig375** [comment]
As this will be supported via #121, this should be part of #120.

**Comment by yoshiask** [comment]
What do you mean by "part of"? As it stands, anyone who wants to use the CSharpMath XAML controls in a UWP project (not Uno) would have to reference the Uno Platform. I guess that's technically fine, but it's really weird.

**Comment by Happypig375** [comment]
`CSharpMath.Uno` will _not_ reference Platform Uno when used on UWP. Read this `csproj`.
https://github.com/verybadcat/CSharpMath/pull/121/files#diff-804e77684648c08794add964c24dabd1R12

**Comment by yoshiask** [comment]
Oh, I get it now, sorry. So is there no point to having `CSharpMath.UWP` specifically, or should everyone on UWP use `CSharpMath.Uno`?

**Comment by Happypig375** [comment]
Platform Uno is supposed to be "UWP everywhere", so it makes sense that UWP is natively supported. Everyone on pure UWP should use `CSharpMath.Uno`. A rename from `CSharpMath.Uno` to `CSharpMath.UWPUno` may better signify this. This issue is now merged into #120.
