### ISSUE TITLE
MathView and TextView width and height calculation does not work with non-100% DPI on Windows

### ISSUE THREAD

**Issue by MartinZikmund** [verybadcat/CSharpMath#136]
### Describe the bug

When display has non-100 % DPI, the height of `TextView` is calculated as significantly bigger than expected on Windows.

### To Reproduce
1. Create a `StackLayout` with two `TextView` controls, both with the following content:

```
\textit{Napětí by se dalo téměř krájet. 
Skupina rytířů vkládá do velkého koše poslední zátěž a přesouvá se 
ke šlapacímu kolu. 
Na povel se začnou pomalu pohybovat a stroj se zachvěje. 
Rameno trebuchetu se jen neochotně sklání k zemi.}

\\

Opatrně ho zajistí mohutnou pojistkou.

\\

Několik mužů umístí těžký kámen do koženého vaku.

\\

Všichni ustoupí do bezpečné vzdálenosti od mohutné dřevěné konstrukce.

\\

Trhnutí lanem a kámen letí vstříc nepřátelské pevnosti.

\\

Desítky očí se nemohou odtrhnout od projektilu.

\\

Doletí?

\\

Pokud se těleso bude pohybovat v blízkosti Země (nebo jakékoliv jiné planety), bude na něj působit tíhová síla. Abychom si celou situaci zjednodušili, tak budeme předpokládat, že těleso se pohybuje v těsné blízkosti povrchu Země a jeho trajektorie bude velmi malá (oboje vzhledem k rozměrům Země).
```

2. Set display scaling in Windows Settings to something higher than 100% (I have 150%).
3.Observe the result has significant space between the texts.

Example from my app:

![image](https://user-images.githubusercontent.com/1075116/85222550-53d65380-b3bc-11ea-8f1d-93dd6150a149.png)

But on 100% scaling display:

![image](https://user-images.githubusercontent.com/1075116/85222566-70728b80-b3bc-11ea-8f79-ec6fec785de0.png)

### Expected behavior

The height should be calculated appropriately regardless of display scaling.

### Environment (please complete the following information):
 - Platform: CSharpMath.SkiaSharp
 - Package Version or Commit: latest
 - Device: Windows 10 PC

**Comment by Happypig375** [comment]
Also note that diacritics are not italicized properly. We need a way to convert `ě` to `\v e` and `ů` to `\r u` automatically because 
![image](https://user-images.githubusercontent.com/19922066/85228708-911bff00-b417-11ea-8441-635564ffb079.png)

**Comment by Happypig375** [comment]
I have no idea what went wrong. Smells like a Xamarin.Forms bug...

**Comment by Happypig375** [comment]
Should be a Xamarin.Forms bug.
![image](https://user-images.githubusercontent.com/19922066/85229551-d7c02800-b41c-11ea-9397-5a385fa1285a.png)

**Comment by Happypig375** [comment]
Hmmm. The spacing increases with the height of the content.

**Comment by FoggyFinder** [comment]
> Should be a Xamarin.Forms bug.

Does it persist across different XF versions?

**Comment by Happypig375** [comment]
Still investigating. I might be wrong on this being a Xamarin.Forms problem.

**Comment by MartinZikmund** [comment]
@Happypig375 actually I discovered the spacing bug in my UWP version, so it is probably something in Painter.Measure 🤔

**Comment by charlesroddie** [comment]
In my usage of CSharpMath I am using a function which is supposed to retrieve the pixels per XF view unit and is defined in each platform project.

```csharp
// Android
Resources.System.DisplayMetrics.ScaledDensity
// iOS
UIScreen.MainScreen.Scale
// UWP
Windows.Graphics.Display.DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel
// Mac
NSScreen.MainScreen.BackingScaleFactor
```

I wonder if there is a better approach to this.

**Comment by Happypig375** [comment]
`Xamarin.Essentials.DeviceDisplay.MainDisplayInfo.Density`?

**Comment by Happypig375** [comment]
My theory is that on higher scales, a larger view box is allocated, but the scale is not taken into account, thus appearing to be smaller. With a fixed width/height, this leads to the view appearing to be scaled down, leading to #137.

**Comment by prepare** [comment]
Hello,

I'm not sure but I think this may related about this issue.

How DPI effect that final pixels size calculation ?
---

_"other than 96 dpi"_

on Windows,
The Typography uses default DPI value on => 96 dpi,
and PointsPerInch= 72 (see the code below),
 to calculate the _scale_to_pixel_ value from  CalculateScaleToPixel() and CalculateScaleToPixelFromPointSize().


These values should be changed to match to current values on your system.
(How to get current DPI value see =>
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow)

an incorrect value may lead to incorrect scale => incorrect heights... etc.
 
```csharp

  const int pointsPerInch = 72; //TODO: should be configurable
        /// <summary>
        /// convert from point-unit value to pixel value
        /// </summary>
        /// <param name="targetPointSize"></param>
        /// <param name="resolution"></param>
        /// <returns></returns>
        public static float ConvPointsToPixels(float targetPointSize, int resolution = 96)
        {
            //http://stackoverflow.com/questions/139655/convert-pixels-to-points
            //points = pixels * 72 / 96
            //------------------------------------------------
            //pixels = targetPointSize * 96 /72
            //pixels = targetPointSize * resolution / pointPerInch
            return targetPointSize * resolution / pointsPerInch;
        }
        /// <summary>
        /// calculate scale to target pixel size based on current typeface's UnitsPerEm
        /// </summary>
        /// <param name="targetPixelSize">target font size in point unit</param>
        /// <returns></returns>
        public float CalculateScaleToPixel(float targetPixelSize)
        {
            //1. return targetPixelSize / UnitsPerEm
            return targetPixelSize / this.UnitsPerEm;
        }
        /// <summary>
        ///  calculate scale to target pixel size based on current typeface's UnitsPerEm
        /// </summary>
        /// <param name="targetPointSize">target font size in point unit</param>
        /// <param name="resolution"></param>
        /// <returns></returns>
        public float CalculateScaleToPixelFromPointSize(float targetPointSize, int resolution = 96)
        {
            //1. var sizeInPixels = ConvPointsToPixels(sizeInPointUnit);
            //2. return  sizeInPixels / UnitsPerEm
            return (targetPointSize * resolution / pointsPerInch) / this.UnitsPerEm;
        }

```

_from https://github.com/LayoutFarm/Typography/blob/master/Typography.OpenFont/Typeface.cs#L304_

**Comment by Happypig375** [comment]
I have noticed the settable resolution in Typography too but I haven't got around to experiment with it.

**Comment by prepare** [comment]
I updated method  CalculateScaleToPixel() and CalculateScaleToPixelFromPointSize() . 
by changing default value of  resolution to -1.

**Comment by Happypig375** [comment]
A problem would be how to get the DPI in a cross-platform way.

**Comment by MartinZikmund** [comment]
> A problem would be how to get the DPI in a cross-platform way. Is Density DPI?

There is a cross platform implementation of display properties in Uno Platform (DisplayInformation class) and Xamarin.Essentials.

**Comment by Happypig375** [comment]
What happens when the view crosses display boundaries?

**Comment by Happypig375** [comment]
Also, MathViews have the same problem.

**Comment by Happypig375** [comment]
This bug does not occur in CSharpMath.Avalonia.

**Comment by Happypig375** [comment]
I'll try to take a Xamarin.Essentials in CSharpMath.Forms and use the density.

**Comment by Happypig375** [comment]
Using `BackgroundColor` as a reference, this bug affects width too.

**Comment by Happypig375** [comment]
Should be fixed in latest commit. Try the nightly packages!

**Comment by MartinZikmund** [comment]
Tested on latest master and works great too :-) . Thanks!
