### ISSUE TITLE
Font Size does not properly scale on Windows

### ISSUE THREAD

**Issue by MartinZikmund** [verybadcat/CSharpMath#137]
### Describe the bug

Fonts don't scale properly on HIDPI screens on Windows.

### To Reproduce

1. Set display scaling to a high percentage in Windows Settings.
2. Run CSharpMath.Forms.Example.UWP
3. Go to Even more tab and note the text size is quite small

For example compare 300% scaling:

![image](https://user-images.githubusercontent.com/1075116/85222631-11614680-b3bd-11ea-88c5-bfdd29c8a8e2.png)

To 100% scaling:

![image](https://user-images.githubusercontent.com/1075116/85222640-20e08f80-b3bd-11ea-9dd3-7ec9bb8a2f3d.png)

### Expected behavior

 The font should get larger, not smaller at higher scale (similarly to the tab text, as you can see in the screenshots.

### Environment (please complete the following information):
 - Platform: CSharpMath.SkiaSharp
 - Package Version or Commit: latest
 - Device: Windows 10

**Comment by Happypig375** [comment]
Probably related to #136.

**Comment by Happypig375** [comment]
Should be fixed in latest commit. Try the nightly packages!

**Comment by MartinZikmund** [comment]
Will check!

**Comment by MartinZikmund** [comment]
Tested on latest master and it works great 👌 . Closing!
