### ISSUE TITLE
How to make non-standard characters bold

### ISSUE THREAD

**Issue by conicgames** [verybadcat/CSharpMath#161]
Hello!

I need to display some titles in bold, but it seems that the \textbf command doesn't work properly on letters with accents (like "àéû"), and with Cyrillic and Chinese characters (I added both regular and bold version of the Chinese fonts). For the Chinese font, I used CSharpMath.Settings.GlobalTypefaces.Add to include both versions.

Is there something special to do for it to work?

Thanks

**Comment by Happypig375** [comment]
Since the current way of loading bold characters make use of the Unicode Mathematical symbols that only support a to z and A to Z, there is currently no way to bold characters outside this range. Improving on this has been recorded at #142 and @charlesroddie has been working on implementing it.

**Comment by Happypig375** [comment]
Merging this issue with #142
