### ISSUE TITLE
Reading an SKTypeface?

### ISSUE THREAD

**Issue by prok155** [verybadcat/CSharpMath#166]
Hello. I would like to display chinese characters on TextView and i have a problem. I've read #20 , but font with chinese characters .ttf weight too much (around 8 MB). Size of my app is very important and i can't allow on use such a big .ttf file. I've tried to do something like this:

var fontManager = SKFontManager.Default;
var typeface = fontManager.MatchCharacter('换');

It is possible to use SKTypeface as a textview typeface? Is there any other way to display Chinese characters without using the custom font files?

**Comment by Happypig375** [comment]
I think you can just
```cs
var reader = new Typography.OpenFont.OpenFontReader();
var typeface = reader.Read(skTypeface.OpenStream().ToSystemIOStream()); // stream is disposed inside Read
```
where `ToSystemIOStream()` wraps a `SKStreamAsset` in a `Stream` with a wrapper class defined by you.

**Comment by prok155** [comment]
I've tried to change SKStreamAsset into a stream, but i got an error:

_SKStreamAsset is not marked as serializable_

Code:

 public static MemoryStream SerializeToStream(object objectType)
        {
            MemoryStream stream = new MemoryStream();
            IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(stream, objectType);
            return stream;
        }

I would like display Chinese/Korean characters without additional .ttf files, maybe this can be achieved in a different way than using SKTypeface? Xamarin default font displays chinese characters correctly, app has some custom controls created with skiasharp and it also has no problems with chinese.

**Comment by Happypig375** [comment]
There are three ways to implement `ToSystemIOStream()`:
- Create a new `System.IO.Stream` subclass wrapping every member of `SkiaSharp.SKStream`
  Pro: No copying of data needed. Con: More code
- Use `SkiaSharp.SKData.Create(SkiaSharp.SKStream)` and call `AsStream` on it
  Pro: Less code Con: Copying of data is needed
- Find a way in SkiaSharp that does this for you (I searched but found nothing)

**Comment by prok155** [comment]
I've searched and skiasharp probably cant do it for me. I've tried the second way:

var fontManager = SKFontManager.Default;
var skTypeface = fontManager.MatchCharacter('换');
var reader = new Typography.OpenFont.OpenFontReader();

SKData skdata = SkiaSharp.SKData.Create(skTypeface.OpenStream());
var typeface = reader.Read(skdata.AsStream());
View.LocalTypefaces = new List<Typography.OpenFont.Typeface> { typeface };


but when i call _reader.Read(skdata.AsStream());_ it returns null. What do you mean by copying data? It's my first time when i use your library and i have some lack of experience.
