### ISSUE TITLE
\angle symbol is not working

### ISSUE THREAD

**Issue by pavledev** [verybadcat/CSharpMath#170]
### Describe the bug
I tried to display angle symbol but when I run app only red rectangle is displayed.
formulaControl.Formula = @"\oint_{S}\vec{E}*d\vec{S}=\oint_{S}E*dS*\angle (\vec{E},d\vec{S})=\oint_{S}E*dS*cos\, 0=\oint_{S}E*ds=E\oint_{S}dS=E*S";

### To Reproduce

1. Call '...'
2. Set '....' to true
3. An InvalidOperationException is thrown with stack trace...

### Environment (please complete the following information):
 - Platform: [e.g. CSharpMath.SkiaSharp, CSharpMath.Forms]
 - Package Version or Commit: [e.g. 0.0.0, a2315b4ac6d9cfdf8cf3dc2aaed37ee2f1dad07a]
 - Device: [e.g. iPhone 6, Pixel 2 XL, Xbox One X]

**Comment by FoggyFinder** [comment]
Wrong repo?

**Comment by pavledev** [comment]
I accidentally posted here instead on wpf-math
