### ISSUE TITLE
Display Errors inline

### ISSUE THREAD

**Issue by BenjaNapo** [verybadcat/CSharpMath#173]
Hi, I want to show LaTex that is only delimited by $$, how can I do it? Because it shows this : 
![WhatsApp Image 2020-10-16 at 19 00 04](https://user-images.githubusercontent.com/25958425/96287406-2b650b80-0fe2-11eb-9228-4412e64a1989.jpeg)

**Comment by FoggyFinder** [comment]
Can you provide some additional information? (At least show the LaTeX)

**Comment by BenjaNapo** [comment]
Ich & er/sie/es 
and
Wir & Sie/sie

In:

```
<math:TextView
    Grid.Column="1"
    Margin="5,0"
    FontSize="12"
    LaTeX="{Binding Associa, Mode=TwoWay}"
    TextColor="{DynamicResource TextColor}"
    VerticalOptions="CenterAndExpand" />
```

**Comment by FoggyFinder** [comment]
You have to add `\` before `&` : `\&`

See: [How to type & in LaTeX?](https://tex.stackexchange.com/questions/36022/how-to-type-in-latex/36023)

**Comment by BenjaNapo** [comment]
Thank you so much !
