### ISSUE TITLE
How to stop blinking placeholder?

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#175]
How to stop blinking placeholder?

**Comment by Happypig375** [comment]
Set `CaretState`.

**Comment by charlesroddie** [comment]
I can't see anything useful there

![image](https://user-images.githubusercontent.com/19760720/97023765-e2670700-154d-11eb-82eb-7ee5f46e1779.png)

I'm trying to get a blinking caret and a non-blinking placeholder.

**Comment by charlesroddie** [comment]
I think a partial revert of https://github.com/verybadcat/CSharpMath/pull/167 is needed.

**Comment by charlesroddie** [comment]
PR here: https://github.com/verybadcat/CSharpMath/pull/176

**Comment by SymboLinker** [comment]
You can make the appearance of the placholder's 2 states equal via Atom.LaTeXSettings by customizing the so called "active" and "passive" placeholder nuclues. (Assuming you use the default color black, you don't need to do anything with the color.)

**Comment by charlesroddie** [comment]
Resolved by https://github.com/verybadcat/CSharpMath/pull/177
