### ISSUE TITLE
Correct behavior for MathPainter LaTeX input "$x$"

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#183]
Should MathPainter LaTeX input allow $s around the LaTeX string?
Previously it did, so $x$ would display as x.
Now it displays as $x$.

I have the feeling it should be lenient and allow $s or no $s around the LaTeX.

**Comment by Happypig375** [comment]
$ is a text-mode construct. To support it correctly and differentiate $ and $$ correctly, TextPainter should be used.
