### ISSUE TITLE
\textbf{} and \textit{} do not work for Russian language

### ISSUE THREAD

**Issue by Aqoolare** [verybadcat/CSharpMath#194]
### Describe the bug
\textbf{} and \textit{} LaTeX functions do not work for Russian language.

### To Reproduce

1. Result of <math:TextView x:Name="textView" LaTeX="\textit{привет}" Margin="15, 5"/> will be the same as <math:TextView x:Name="textView" LaTeX="привет" Margin="15, 5"/>
2. But content of <math:TextView x:Name="textView" LaTeX="\textit{hello}" Margin="15, 5"/> will change font attribute
### Expected behavior
Latex functions apply to Russian

### Environment (please complete the following information):
 - Platform: [CSharpMath.Forms]
 - Package Version or Commit: [e.g. 0.5.1]
 - Device: [Pixel 2 Q 10.0]

**Comment by Happypig375** [comment]
Merging issue into #142
