### ISSUE TITLE
Font information

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#2]
After looking into the code, I am considering implementing #1 myself.
However, I think [this library](https://github.com/LayoutFarm/Typography) can be used (with git-submodule) as a cross-platform typography API instead of unnecessarily implementing every platform with their own completely different APIs (main issue: iOS has CoreText, Windows has GlyphTypeface, Android has... nothing - duh).
More code reuse can be achieved.
What do you think?

**Comment by verybadcat** [comment]
The main reason I am doing iOS first is that it is a great help to be able to run the Xcode and C# versions of the program side-by side. If two coordinates are different, I can ask why, and usually find the bug pretty quickly.

I definitely agree that in the long run, a cross-platform "front end" is a great idea. You might want to take a look at https://github.com/harfbuzz/harfbuzz. It is designed to work with SkiaSharp and Xamarin. I've used SkiaSharp in a project. Their API took some getting used to -- but every API does. I've never used HarfBuzz. It also appears to be much more widely used than Typography. And note the licenses:

https://github.com/harfbuzz/harfbuzz/blob/master/COPYING
https://github.com/LayoutFarm/Typography/blob/master/LICENSE.md

At a first glance, the HarfBuzz one looks much better.

One big part may be generating the MathTable. See https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath/Resources/latinmodern-math.json. That was another big advantage of starting with iOS -- I didn't have to generate that file; I could just convert theirs from plist. That said, it may be the kind of thing that can grow gradually. You won't need the whole thing to get decent results for a lot of cases.

**Comment by charlesroddie** [comment]
Can we list the

    Static font information
    Dynamic font information

That we need for CSharpMath?

It may be possible to make a component that can read and write an Xml or Json file with this information.

wpf-math has this information (@ForNeVeR I see you've done some work on this recently):
https://github.com/ForNeVeR/wpf-math/blob/master/docs/prepare-font.md
https://github.com/ForNeVeR/wpf-math/blob/master/src/WpfMath/Data/DefaultTexFont.xml

**Comment by Happypig375** [comment]
The information will be incomplete if all information are to be extracted via Typography due to the lack of support of glyph names.
I am waiting @prepare to be back and continue implementing this.

-----

I am confused why we need glyph names to be extracted. In CSharpMath.Ios, glyph indices are used everywhere which can basically used to query everything needed. I don't see the value in glyph names. Glyph indices should be used instead.

**Comment by Happypig375** [comment]
Merged into #12
