### ISSUE TITLE
Fonts with Chinese characters?

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#20]
How hard would it be to allow Chinese text in text mode?
Would this be done by allowing the usage of an arbitrary font?
Would there be any additional work needed?

**Comment by Happypig375** [comment]
By the way, as shown in the bottom of the README, I plan to create a CSharpMath.Fonts package that would be a collection of fonts to support all Unicode codepoints in 0.2.0.

**Comment by Happypig375** [comment]
Did that method work?

**Comment by charlesroddie** [comment]
I can't read it but it looks to me like it works:
![mh7optr](https://user-images.githubusercontent.com/19760720/45619957-14eecd80-ba73-11e8-91f4-01c4eb36a3b2.jpg)

**Comment by Happypig375** [comment]
The text definitely makes sense. That means it is definitely working! 👏

**Comment by Happypig375** [comment]
By the way, the number should use a dot (.) as the decimal separator. Maybe it should depend on the Chinese CultureInfo specifically instead of the default CurrentCulture of ToString?

**Comment by charlesroddie** [comment]
I think that's because it was done on @FoggyFinder 's system using Russian settings.
