### ISSUE TITLE
CSharpMath not Showing LaTex text

### ISSUE THREAD

**Issue by kmpundu** [verybadcat/CSharpMath#202]
I am trying to render LaTex in xamarin forms using CSharpMath.forms. However, the LaTex text is not showing. I have observed that in the Android emulator's screen the Mathview/Textview is  occupying space when the app is run (  Mathview/Textview  is with beige background in attached image) but the content is not showing. I even tried using Code behind to programmatically display it but the result is the same. I am using Visual Studio 2019 Community Version.
![emulator screenshot](https://user-images.githubusercontent.com/93823717/140613807-21fd37a6-502f-4fd1-829b-9cfd98cd0909.png)
The code is as below

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:math="clr-namespace:CSharpMath.Forms;assembly=CSharpMath.Forms"
             x:Class="MathApp.Mathematics.IndexNotationPage">

    <StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" x:Name="LatexView">
    <math:MathView x:Name="View" Opacity="1"
                   HorizontalOptions="FillAndExpand"
                   VerticalOptions="FillAndExpand">
        Using integration by parts, solve: $\int\left(x\ln x\right)dx$
    </math:MathView>
        <math:TextView LaTeX="Text $3+4+5+6\cdot7^{5x^2}+a_n$ More text $$\int^5_2x^3+x^2-x-3dx$$ Text" 
                       FontSize="14" BackgroundColor="Beige"/>
        <Label Text="I can't see Latex math above"/>
        <Button Text="latex view" x:Name="latexButton" Clicked="latexButton_Clicked"/>
    </StackLayout>
</ContentPage>`

I have included the namespace in the ContentPage:
` xmlns:math="clr-namespace:CSharpMath.Forms;assembly=CSharpMath.Forms"`
Dependacies as in picture below

![Dependancies](https://user-images.githubusercontent.com/93823717/140614436-ad64e084-51b8-4d44-8138-a8e09f7792cf.png)
I have also observed the following warnings. If they have anything to do with it how do I resolve them?

>
Warning		Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
There was a conflict between "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll].
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll
          Project file item includes which caused reference "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll".
            System.Numerics.Vectors
    References which depend on "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
        C:\Users\User\.nuget\packages\csharpmath.rendering\0.5.1\lib\netstandard2.0\CSharpMath.Rendering.dll
          Project file item includes which caused reference "C:\Users\User\.nuget\packages\csharpmath.rendering\0.5.1\lib\netstandard2.0\CSharpMath.Rendering.dll".
            C:\Users\User\.nuget\packages\csharpmath.rendering\0.5.1\lib\netstandard2.0\CSharpMath.Rendering.dll
            C:\Users\User\Documents\HighSchoolScienceApp\HighSchoolScienceApp\HighSchoolScienceApp\bin\Debug\netstandard2.0\HighSchoolScienceApp.dll
            C:\Users\User\.nuget\packages\csharpmath.forms\0.5.1\lib\netstandard2.0\CSharpMath.Forms.dll
            C:\Users\User\.nuget\packages\csharpmath.skiasharp\0.5.1\lib\netstandard2.0\CSharpMath.SkiaSharp.dll	MathApp.Android			

Kindly assist

**Comment by Happypig375** [comment]
I'd suggest starting from our samples and modifying them, because Xamarin tooling sometimes is quirky.

**Comment by FoggyFinder** [comment]
It's probably the same as #198

**Comment by kmpundu** [comment]
I've come to discover that the issue is coming from the version of CSharpMath. When I downgraded to version 0.3.0, the LaTeX symbols started showing. If only there can be a solution to work with later versions
