### ISSUE TITLE
0.1.0 - 0.1.4 SkiaSharp Update have been released!

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#21]
Coinciding with the 1st birthday of CSharpMath ([October 6](https://github.com/verybadcat/CSharpMath/commit/455bb457a88d6717a4eca459f3b33714fd41121b)), the [0.1.0 SkiaSharp Update](https://github.com/verybadcat/CSharpMath/releases/tag/v0.1.0) has been released. 🎉🎉🎉🎂🍰🎂🍰🎂🎉🎉🎉🎉🎉🎉🎂🍰🎂🍰🎂🎉🎉🎉🎉🎉🍰🎂🍰🎉

Edit: 0.1.1 has been released, which fixes issues mentioned below.

This supersedes #17.
## Features
- SkiaSharp and Xamarin.Forms platform support
- CSharpMath.Forms.Example (an actual application that you would want to use)
- Partial support for global-level LaTeX (only available for SkiaSharp and Xamarin.Forms)
- Easier porting to other platforms with CSharpMath.Rendering, CSharpMath.Settings static class in CSharpMath.Rendering package for easier settings
- Arbitrary TTF and OTF font support via [Typography](https://github.com/LayoutFarm/Typography) (SkiaSharp and Xamarin.Forms only) (Thanks @prepare)
- Accents
- Overlines and underlines
- Colors
- Raise boxes
- \\TeX
- Proper support for primes
- Beautiful \\mathbb capital latters (SkiaSharp and Xamarin.Forms only)
- Bugfix for nested \\sqrt
- LaTeX brace groups now stored in a new Group atom so that they are preserved when converting back to LaTeX strings
- Fixed limits in text style, \sin, \cos etc are now non-limitable
- The CSharpMath core package now targets .NET Standard 1.1!
- CSharpMath now buildable in .NET Native (Thanks @FoggyFinder)
- CSharpMath now has an icon
- Major internal restructuring
- Optimizations all over the place
- Plus a lot more...
## What's next?
- #11 MathEditor port
- #4 Merge with wpf-math
  - Refactor TextAtoms and MathAtoms to have common atoms
  - Refactor MathAtoms to get rid of MathAtomType and AtomCloner
  - Unit tests (and picture comparisons)
  - Tavis CI integration
## After that...
- Subpixel rendering
- Getting started
- Documentation of MathPainter on both NuGet and GitHub wiki
- [Extra docs on Measure](https://github.com/verybadcat/CSharpMath/issues/12#issuecomment-405013645)
- [2 new wiki pages](https://github.com/verybadcat/CSharpMath/issues/12#issuecomment-402373426)
- Document release procedure
- Promotion of the merged project
- Also native support for all popular platforms
- Implement \\middle
- Fix `1 \\ { 2 \\ 3 }`'s spacing between 1 and 2
![image](https://user-images.githubusercontent.com/19922066/42049804-b52f8aba-7b39-11e8-8ae0-261fe49d7950.png)
- A way to limit scrolling to horizontal only or vertical only
- Improve loading times of CSharpMath.Forms.Android.Example in Release mode
- `However, it is also not yet complete as in not being able to SeparateThisReallyLongWordWhichIsSoLongThatItSpansAcrossTheEntirePageAndWontStopEvenWhenPartOfItIsOutOfBounds.`
![image](https://user-images.githubusercontent.com/19922066/43326540-b3f37620-91eb-11e8-86e4-e40f3aef9d31.png)
###### [ˢᵗᵘᶠᶠ ᶠᵒʳ ᵗʰᵉ ᶠᵃʳ ᶠᵘᵗᵘʳᵉ](https://github.com/verybadcat/CSharpMath#a-sneak-peek-at-the-future)

**Comment by FoggyFinder** [comment]
@Happypig375  `\textbf` command doesn't work

**Comment by Happypig375** [comment]
Also for 0.1.1: Remove the two experimental buttons in Forms.Example. [Previous discussion](https://stackoverflow.com/questions/52704798/rendering-mathematical-equations-from-a-string-in-latex-form-in-uwp/52705791?noredirect=1#comment92485392_52705791)

**Comment by FoggyFinder** [comment]
> I remember having fixed this but the fix did not appear in the codebase. Maybe I forgot to commit it. Anyways, a re-fix is on track for 0.1.1.

Nice. Do you know already approximate release date?

**Comment by charlesroddie** [comment]
> 
> 
> @Happypig375 `\textbf` command doesn't work

Italics stopped working too.

**Comment by Happypig375** [comment]
>Nice. Do you know already approximate release date?

Today.
>Italics stopped working too.

Should be also fixed.

**Comment by charlesroddie** [comment]
Usable line length is not adjusted when there is "\par". This leads to incorrect wrapping. E.g. "give" is not fully displayed in the line "This is..." which starts with "\par":
![image](https://user-images.githubusercontent.com/19760720/47235216-49d2a500-d3d0-11e8-8ed5-fd88678c0cc6.png)

**Comment by Happypig375** [comment]
@charlesroddie Somehow the notification for your comment was identified as spam. Anyways, 0.1.2 is now available to fix this.

**Comment by charlesroddie** [comment]
Great. Any chance of a CSharpMath.SkiaSharp 0.1.2 which depends on the other 0.1.2 update (to keep packagereferences clean)? Thanks!

**Comment by Happypig375** [comment]
NuGet just needs a while for validating the packages. Each takes different time, independent of the order I uploaded them. In this case, SkiaSharp and Ios were successful first, and the others just needed a few more minutes.

**Comment by Happypig375** [comment]
Sorry for misinformation.

Upload time 19:56
CSharpMath 19:57
CSharpMath.Forms 19:58
CSharpMath.Ios 19:58
CSharpMath.Rendering 20:01
CSharpMath.SkiaSharp 20:18

**Comment by angelklim** [comment]
Hi @Happypig375. The lower limits of integration are getting cut off. 

![integ_cutoff1](https://user-images.githubusercontent.com/44362284/48132262-eef4e500-e2cd-11e8-80e1-47a521b7fd5a.PNG)

**Comment by Happypig375** [comment]
@angelklim
Can you please paste the LaTeX source, TextPainter settings and the NuGet version? The displayed content does not seem right to me.

**Comment by angelklim** [comment]
TextPainter settings are default, NuGet v0.1.2
This uses \int \limits_3^7. It looks ok with just \int_3^7 albeit a little cramped. Just \int \limits_n still cuts off the lower limit though.

**Comment by Happypig375** [comment]
@angelklim Fixed in 0.1.3

**Comment by EmilyWoodhouse1** [comment]
![image](https://user-images.githubusercontent.com/45573905/49395939-bfe85c80-f72f-11e8-8970-f00a06acc0c2.png)
Surds in fractions are getting cut off, is it possible to move the number for the root - maybe lower and further left?

**Comment by Happypig375** [comment]
The number in the degree of the surd should have been smaller. I'll check the code.

**Comment by Happypig375** [comment]
Superseded by #29.
