### ISSUE TITLE
How to control the size of an Image output

### ISSUE THREAD

**Issue by file-acomplaint** [verybadcat/CSharpMath#214]
Hello folks, thanks for the awesome library and sorry for the following stupid question!

I'm using this on a platform that's a bit out there, so I'm currently repurposing the SkiaSharp frontend to output an image like in the example. Is there any way to control the resolution of the image, basically scaling up by a factor?

I imagine it would be done by passing a specification to `new MathPainter`?

**Comment by charlesroddie** [comment]
MathPainter has a FontSize property. I don't know what the unit is for that, but you can certainly use it to scale things up.

**Comment by file-acomplaint** [comment]
Thank you, that was exactly what I was looking for!

[This wiki page](https://github.com/verybadcat/CSharpMath/wiki/Documentation-of-public-facing-APIs-of-CSharpMath.Rendering,-CSharpMath.SkiaSharp-and-CSharpMath.Forms-MathViews) was also helpful for me.
