### ISSUE TITLE
Can't use matrix

### ISSUE THREAD

**Issue by rennmaus-coder** [verybadcat/CSharpMath#219]
### Describe the bug
When I try to use \matrix, there is an error that tells me that \matrix is unknown. I am not sure if that's a bug or a missing feature

### To Reproduce
Make a MathView and enter some matrix
Error shows

### Expected behavior
Display a Matrix 

### Environment (please complete the following information):
 - Platform: Xamarin.Forms / CsharpMath.Forms
 - Package Version or Commit: 0.3.0 (because the latest didn't work at all)
 - Device: Galaxy a8

**Comment by Happypig375** [comment]
as you probably found by yourself, the usage is `\begin{matrix}` and `\end{matrix}`.
