### ISSUE TITLE
How can I fix System.Numerics.Vectors conflict?

### ISSUE THREAD

**Issue by ViDanMaster** [verybadcat/CSharpMath#221]
I am currently using CSharpMath 0.3.0 in my Xamarin.Forms application, because when I am trying to update it to 0.5.1, there is a System.Numerics.Vector conflict, and the LaTeX won't render. I don't know if these 2 things are related, but regardless can I do anything about this to fix it (to get it to render the LaTeX)?

**Comment by NGC224-Andromeda** [comment]
I seem to have the same issue. Would be nice to know the fix to this.

**Comment by NGC224-Andromeda** [comment]
I have also noticed that it makes the place for the render but not showing up. It's the basic Xamarin template with the 0.5.1. CSharpMath.
![Screenshot_1676595114](https://user-images.githubusercontent.com/118385317/219521677-a7571e92-15fd-48ad-9f0d-301ee7b71038.png)

**Comment by ViDanMaster** [comment]
If anyone is wondering, if you are using CSharpMath above 0.4.0 you also need to add SkiaSharp as a nugget package to render LaTeX
