### ISSUE TITLE
Does CSharpMath have a function that converts/parses plain text into LaTeX code and returns it as a C# String?

### ISSUE THREAD

**Issue by AlexSchmidt2019** [verybadcat/CSharpMath#224]
Hi.

Is there a function or a way in CSharpMath that I can use which parses plain text like: `x=a/b` to LaTeX code?

Here is what I am expecting: So in my winform app, the user doesn't know LaTeX, he would enter an equation in plain text like `x=a/b`, and he will expect that text to be rendered in the form. From what I can tell, CSharpMath does a great job in rendering LaTeX on the form, but the problem is that it required LaTeX as input. Is there a way to convert that plain text into LaTeX code so I can feed the result to the renderer?

I have been looking for days non stop into this problem. Any help will be massive, thanks in advanced.

**Comment by Happypig375** [comment]
This library does not parse plan text equations.

https://github.com/asc-community/AngouriMath can do what you want. It can parse plan text equations and output LaTeX.

**Comment by AlexSchmidt2019** [comment]
> 

That solves my problem. Thanks a lot

**Comment by Happypig375** [comment]
@AlexSchmidt2019 You're welcome!
