### ISSUE TITLE
Can you change the font size of what is rendered in an SKControl as LaTeX $$equations$$?

### ISSUE THREAD

**Issue by AlexSchmidt2019** [verybadcat/CSharpMath#225]
No, changing the font size property of the SKControl doesn't do anything.

I am using SkiaSharp with CSharpMath for this.

Take a lot at this simple PaintSurface event body:

`private void SkControl_PaintSurface(object sender, SKPaintSurfaceEventArgs e)`
        `{`
              `e.Surface.Canvas.Clear();`
              `var painter = new TextPainter();`
              `painter.LaTeX = @"$$\frac{a}{b}$$";`
              `painter.Draw(e.Surface.Canvas);`
        `}`

This function will draw a simple a/b formula on the screen as shown in the screenshot below below:
![image](https://github.com/verybadcat/CSharpMath/assets/54552819/77a81fa5-b254-465b-a884-ff3e0f4631af)

I would like to increase the font size of the result equation formula? Is this even possible? If yes, how. 

I have tried to use some LaTeX syntax but it gave me some errors. (I don't know LaTeX I am just looking for syntax on google and I am not sure how do I use it.)

Thanks in advance.

**Comment by Happypig375** [comment]
You can either [scale the canvas](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.scale?view=skiasharp-2.88#skiasharp-skcanvas-scale(system-single)) or set the FontSize property of the TextPainter.

**Comment by AlexSchmidt2019** [comment]
> You can either [scale the canvas](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.scale?view=skiasharp-2.88#skiasharp-skcanvas-scale(system-single)) or set the FontSize property of the TextPainter.

So to which object does this TextPainter property that you mentioned belong? How can I access it?

**Comment by Happypig375** [comment]
@AlexSchmidt2019 You already have an instance of TextPainter in your simple code.

**Comment by AlexSchmidt2019** [comment]
> @AlexSchmidt2019 You already have an instance of TextPainter in your simple code.

Yea I just did it, thanks for the help it works. Huge thanks!

**Comment by Happypig375** [comment]
You're welcome!
