### ISSUE TITLE
Hello, I would like to know if it works in WPF.

### ISSUE THREAD

**Issue by pomaton12** [verybadcat/CSharpMath#228]
Hello, I would like to know if CSharpMath works in C# WPF to render Formulas.

**Comment by charlesroddie** [comment]
Yes, skiasharp works on wpf so use that and draw on the canvas as in the main .md instructions.

**Comment by pomaton12** [comment]
`        public MainWindow()
        {
            InitializeComponent();

            var painter = new CSharpMath.Forms.MathView
            {
                LaTeX = "a_b",
            };

            MyPanel.Children.Add(painter);

        }`

I am trying to add a formula to a MyPanel canvas panel in c# wpf

I have the ERROR message: cannot convert from 'CSharpMath.Forms.MathView' to 'System.Windows.UIElement'
