### ISSUE TITLE
\sqrt seems to have problem in CSharpMath.SkiaSharp

### ISSUE THREAD

**Issue by zqymoe** [verybadcat/CSharpMath#229]
Hello, I'm using CSharpMath.SkiaSharp. When my latex is `v_\frac{x}{2}=\sqrt{\frac{v_0^2+v_t^2}{2}}`, I got the result as follows:
![屏幕截图 2023-12-10 222830](https://github.com/verybadcat/CSharpMath/assets/134846173/e9e05f22-143a-4706-b0d2-15de1854981a)
It looks strange!
I also try `\sqrt{\sqrt{\frac{1}{2}}}`, but:
![屏幕截图 2023-12-10 223300](https://github.com/verybadcat/CSharpMath/assets/134846173/306dad22-72e7-4d90-912b-111db376ccab)
I don't know if this is a bug. I just use `MathPainter`, maybe there are other solutions🤔

**Comment by Happypig375** [comment]
Are you using an OTF font that supports [the OpenType MATH Table, specifically the MathVariants table](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathvariants-table)? If your font has no such information, it won't typeset beautifully.
