### ISSUE TITLE
MAUI XAML without skiasharp

### ISSUE THREAD

**Issue by cagriy** [verybadcat/CSharpMath#235]
Just wanted to check:

```
    <math:MathView x:Name="View" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        \frac\sqrt23
    </math:MathView>
```

Is there a practical way to use this notation in MAUI ?

Many thanks

**Comment by charlesroddie** [comment]
You could research the relationship between xaml text and classes to see if it is possible to write dotnet code from the markup language (maui is the best repo do discuss that since it controls this markup language), or could create a library to enable what you want.
