### ISSUE TITLE
How can I get the size of the rendered text ?

### ISSUE THREAD

**Issue by cagriy** [verybadcat/CSharpMath#237]
Apologise if I am asking a Skiasharp question but have been struggling with this.

I am using `painter.Draw(_skCanvas);` to put TextPainter output onto a canvas. The text has an arbitrary length.

This is for a mobile application and I can adjust the height of the SKCanvasView as much as needed.

Is there a practical way for me to estimate the height of the final output on the canvas so that I can resize SKCanvasView accordingly ? To stop it either being too tall with a blank at the bottom or too short causing text to be clipped. I can do this before or after the Draw method is executed.

Thanks in advance.

**Comment by Happypig375** [comment]
`painter.Measure(_skCanvas.LocalClipBounds.Width)`

**Comment by cagriy** [comment]
Thanks a lot @Happypig375
