### ISSUE TITLE
Question: Is it possible to make the equations selectable?

### ISSUE THREAD

**Issue by sadqiang** [verybadcat/CSharpMath#25]
It might be a silly question. Is it possible to make the equation selectable in a PDF viewer?

```
using CSharpMath.SkiaSharp;
using SkiaSharp;

class MainClass
{
    public static void Main(string[] args)
    {
        using (var stream = new SKFileWStream("document.pdf"))
        using (var document = SKDocument.CreatePdf(stream))
        using (var canvas = document.BeginPage(500, 500))
        {
            // create the paint for the circle border
            var circleBorder = new SKPaint
            {
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                Color = SKColors.Red,
                StrokeWidth = 5
            };
            // draw the circle border
            canvas.DrawCircle(100, 100, 40, circleBorder);

            // create the paint for the path
            var pathStroke = new SKPaint
            {
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                Color = SKColors.Green,
                StrokeWidth = 5
            };

            // create a path
            var path = new SKPath();
            path.MoveTo(160, 60);
            path.LineTo(240, 140);
            path.MoveTo(240, 60);
            path.LineTo(160, 140);

            // draw the path
            canvas.DrawPath(path, pathStroke);

            // create the paint for the text
            var textPaint = new SKPaint
            {
                IsAntialias = true,
                Style = SKPaintStyle.Fill,
                Color = SKColors.Orange,
                TextSize = 80
            };
            // draw the text (from the baseline)
            canvas.DrawText("SkiaSharp!", 60, 160 + 80, textPaint);

            var painter = new TextPainter
            {
                Text = @"$\displaystyle\int_a^b f(x)\,\mathrm{d}x=F(b)-F(a)$"
            };
            painter.Draw(canvas, 320, 60, 100);

            document.EndPage();
        }
    }
}

```

**Comment by charlesroddie** [comment]
This question could be about SkiaSharp, how to create links in an SKDocument, or independent of SkiaSharp and about how to manipulate pdfs. It also could be about links, or it could be about focus within pdf documents. It seems very ambiguous. Regardless, its unlikely that CSharpMath can help you.

It is interesting that SkiaSharp can be used to create pdfs and that therefore CSharpMath can be used to create pdfs.

**Comment by sadqiang** [comment]
@charlesroddie : `canvas.DrawText("SkiaSharp!", 60, 160 + 80, textPaint);` can be selected and searched because it is not blended to be a graphic object. But ` painter.Draw(canvas, 320, 60, 100);` blend the equation into a graphic object  that cannot be selected or searched.

**Comment by charlesroddie** [comment]
OK I get it select = select and highlight text for copying
PDF does that badly even with ordinary text. So with maths there is no chance. But anything not in maths mode would probably be selectable.

**Comment by Happypig375** [comment]
CSharpMath draws all text as graphics, not as text. This is a byproduct of using the Typography library to read the typeface info and glyph contours, not SKTypeface of SkiaSharp. To use the DrawText method to draw text, CSharpMath would need to read the font file twice, which sounds like a performance loss.

**Comment by sadqiang** [comment]
OK. Thank you for responding!

**Comment by prepare** [comment]
@Happypig375,

for Pdf, selectable math expression adds  values to this lib.
and this is possible. But it need more works.

Since now you know exact position of each glyph.
Lets draw it with a character at that position.
