### ISSUE TITLE
Add OTF Font in Xamarin.Forms

### ISSUE THREAD

**Issue by donmesserli** [verybadcat/CSharpMath#28]
Is it possible to use a different OpenType font than the one included in the library without building the library from source? Are there calls my app can make to load and use a font? If so, can you provide instructions on how to do it?

**Comment by charlesroddie** [comment]
Yes see https://github.com/verybadcat/CSharpMath/issues/20

**Comment by Happypig375** [comment]
@donmesserli Please respond if the referenced issue helped you :smile:

**Comment by donmesserli** [comment]
I saw that question; but the answer is very terse. Can you provide a code snippet and tell me where in my application I need to call it?

**Comment by donmesserli** [comment]
I'm doing this in Xamarin.Forms. Not using a painter.

**Comment by charlesroddie** [comment]
Then try `CSharpMath.Settings.GlobalTypefaces` as described in the linked issue.

**Comment by donmesserli** [comment]
That's what I want to do; but I still need a code snippet.

**Comment by charlesroddie** [comment]
The code is as above with GlobalTypeFaces instead of painter.LocalTypefaces.
```csharp
using (System.IO.Stream otf = System.IO.File.OpenRead fileName)
{
    CSharpMath.Settings.GlobalTypefaces.Add(new Typography.OpenFont.OpenFontReader().Read(otf));
}
```
Put this somewhere where it will be called when your app starts, i.e. before rendering happens.

**Comment by Happypig375** [comment]
Also applicable:
```cs
System.IO.Stream otf = ...;
CSharpMath.Forms.MathView mathView = ...;
mathView.LocalTypefaces.Add(new Typography.OpenFont.OpenFontReader().Read(otf));
```

**Comment by Happypig375** [comment]
@donmesserli Please respond if the answers helped you 😃
