### ISSUE TITLE
0.2.0 Editor Update has been released!

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#29]
0.2.0 Editor Update - ~~the final minor update of CSharpMath before becoming MathDisplay.NET~~ (Edit by the time of 0.3.0 release: Not yet... I'll do it when I have time.). 
## Features
- A math editor! There are two ways to use it, below are CSharpMath.Forms examples:
1. Having a custom keyboard:
```cs
//from XAML
SkiaSharp.Views.Forms.SKCanvasView canvasView = ...;
Xamarin.Forms.Button button = ...;

var painter = new CSharpMath.SkiaSharp.MathPainter
{ /*set all properties aside from LocalTypefaces, FontSize, LineStyle,
    MathList, LaTeX and Source (these are ignored)*/ };
var keyboard = new CSharpMath.Rendering.MathKeyboard(/*optional fontSize*/)
{ /*set Fonts, LineStyle and InsertionIndex here*/ };
button.Pressed += (sender, e) => keyboard.KeyPress(CSharpMath.Editor.MathKeyboardInput.SmallX /*or any key*/);
keyboard.RedrawRequested += (sender, e) => canvasView.InvalidateSurface();
canvasView.PaintSurface += (sender, e) => {
  e.Surface.Canvas.Clear();
  //for any DrawDisplay overload, arguments after canvas are the same as Draw
  CSharpMath.SkiaSharp.MathPainter.DrawDisplay(painter, keyboard.Display, e.Surface.Canvas);
  keyboard.DrawCaret(
    new CSharpMath.SkiaSharp.SkiaCanvas(e.Surface.Canvas, SkiaSharp.SKStrokeCap.Butt, false),
    CSharpMath.Rendering.CaretShape.IBeam);
};
```
![screen](https://user-images.githubusercontent.com/19922066/50734289-f5251600-11d7-11e9-9d48-01dba5b3c2cc.gif)
2. Using the default keyboard:
```cs
//from XAML
SkiaSharp.Views.Forms.SKCanvasView canvasView = ...;
CSharpMath.Forms.MathKeyboard keyboard = ...;

var painter = new CSharpMath.SkiaSharp.MathPainter
{ /*set all properties aside from LocalTypefaces, FontSize, LineStyle,
    MathList, LaTeX and Source (these are ignored)*/ };
keyboard.RedrawRequested += (sender, e) => canvasView.InvalidateSurface();
canvasView.PaintSurface += (sender, e) => {
  e.Surface.Canvas.Clear();
  //for any DrawDisplay overload, arguments after canvas are the same as Draw
  CSharpMath.SkiaSharp.MathPainter.DrawDisplay(painter, keyboard.Display, e.Surface.Canvas);
  keyboard.DrawCaret(e.Surface.Canvas, CSharpMath.Rendering.CaretShape.IBeam);
};
```
![screen](https://user-images.githubusercontent.com/19922066/50734435-2272c380-11da-11e9-9781-c1cf3072cb79.gif)
- An analog clock in CSharpMath.Forms.Example - credits to https://github.com/sadqiang at #27
![image](https://user-images.githubusercontent.com/19922066/50588361-ad8f4900-0ebc-11e9-9ca7-f8870f780a00.png)
## Why did it take so long?
October was the month when most of the logic were ported successfully. However, with limited understanding of .xib files which are Xcode UI definitions, I tried to literally port the XML contents to C#, but resulted in messy code. There went November.
A port of the keyboard UI code to XAML costed a December's worth of time.
Not much happened here in January, mostly waiting for potential bug reports.
Welp, that was time badly spent. I'm sorry for that.
## Current plans
- #4 Merge with wpf-math
  - F# instead of C# (just as interoperable but much more maintainable)
  - Refactor TextAtoms and MathAtoms to have common atoms
  - Refactor MathAtoms to get rid of MathAtomType and AtomCloner
  - Unit tests (and picture comparisons)
  - Tavis CI integration
  - An intuitive README for getting started
  - Documentation on both NuGet and GitHub wiki
  - Document release procedure
  - Promote awareness!!
  - Native platform support for the popular ones
- Implement \\middle
- Optimize loading times of the Android example project
## A new start
The merge with [wpf-math](https://github.com/FoRNeVeR/wpf-math) is happening in [this repository](https://github.com/charlesroddie/MathAtom). Please watch the repository for future updates!

Supersedes #21.

**Comment by sadqiang** [comment]
In the animation given above, instead of showing `xxxxxx...` (typing `x` multiple times), why don't we show something like `\int_a^b f(x)\, \mathrm{d}x=F(b)-F(a)`, for example?

**Comment by Happypig375** [comment]
To show the actual code for implementing one button, small x in this case.

**Comment by charlesroddie** [comment]
Great work @Happypig375. For keyboard input into a Xamarin.Forms control I think the best thing is an Effect (or otherwise custom renderer) on UWP that handles focus and keyboard input. Looking into this.

**Comment by Happypig375** [comment]
Superceded by #104
