### ISSUE TITLE
Is there any binding mechanism for displaying LaTeX formulas?

### ISSUE THREAD

**Issue by vadim1195** [verybadcat/CSharpMath#36]
I'm trying to use MathView control with MVVM and getting the same error
> Error: Position 16:46. No property, bindable property, or event found for 'LaTeX', or mismatching type between value and property. (MHelper)

So, this is the page where I'm trying to bind property from ViewModel
``` DerivativePage.xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:vm="clr-namespace:MHelper.ViewModels"
             xmlns:math="clr-namespace:CSharpMath.Forms;assembly=CSharpMath.Forms"
             x:Class="MHelper.Views.DerivativePage"
             Title="{Binding Title}">
    <ContentPage.BindingContext>
        <vm:DerivativeViewModel />
    </ContentPage.BindingContext>
    <ContentPage.Content>
            <math:MathView x:Name="TextView" LaTeX="{Binding ResultExpression}" HorizontalOptions="FillAndExpand"/>
    </ContentPage.Content>
</ContentPage>
```

``` DerivativeViewModel.cs
public class DerivativeViewModel : BaseViewModel
{
        public string SourceExpression { get; set; }
        public string ResultExpression { get; set; }
}
```

But `ResultExpression` and `LaTeX` properties are the same type "string". How can I use this control with MVVM?[](url)

**Comment by Happypig375** [comment]
Thanks, will investigate tomorrow.

**Comment by charlesroddie** [comment]
@vadim1195 your `ResultExpression` must be be a mutable variable that notifies on changes to its state. E.g. `INotifyPropertyChanged` or `ReactiveObject` or `Gjallarhorn.Mutable`. So in the view (if you ditch the XAML) you can subscribe to the changed event to update the `LaTeX` property.

**Comment by charlesroddie** [comment]
@vadim1195 You ccould do a PR to add a `LaTeX` `BindableProperty` [here](https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath.Forms/MathView.cs). CSharpMath.Forms is entirely @Happypig375 's domain but there is similar code there already so it wouldn't surprise me if a PR got accepted.

But in my opinion it's better to wean yourself off XAML.

Take it from @dsyme (from [F# exchange](https://skillsmatter.com/skillscasts/13437-towards-f-sharp-5-0))

![2019-04-23](https://user-images.githubusercontent.com/19760720/56539790-ccdede80-655e-11e9-867f-b348f6cb3ab5.png)

`not` in the XAML world:

![2019-04-23 (2)](https://user-images.githubusercontent.com/19760720/56539796-cf413880-655e-11e9-8297-3e4510576d22.png)

**Comment by Happypig375** [comment]
@charlesroddie What a coincidence, I watched "Towards F# 5.0" a few days ago as well!

**Comment by Happypig375** [comment]
@vadim1195 I might have to hack the implementation because it requires two BindableProperties that update each other.

**Comment by Happypig375** [comment]
@vadim1195 Please see if CSharpMath.Forms 0.2.1 works. To be honest, since I started learning F# + Fabulous, I had been excited to unlearn most of MVVM and data binding. So, if there's any bugs with this, please be sure to attach a zipped project so that I can test whether my fix succeeds. Thanks.
