### ISSUE TITLE
Arrows over vectors

### ISSUE THREAD

**Issue by EmilyWoodhouse1** [verybadcat/CSharpMath#37]
**Describe the bug**
Vectors from point A to B are typically listed as AB with an arrow over the top, like in this image from a textbook:
![image](https://user-images.githubusercontent.com/45573905/57539014-7389f400-7341-11e9-92b6-27c78d5c8b5c.png)

I am trying to specify this vector using $\vec{AB}$. In most cases the arrow is getting cut off so only a small dot appears above the letters: 
![image](https://user-images.githubusercontent.com/45573905/57539183-d2e80400-7341-11e9-965c-edcf23b9e4e3.png)

If the letters are below another row of text the arrows appear nicely. If I try to replicate this effect by specifying a new line in front of the vector, the whole text is shuffled down an look out of line.
The hint:
[FormulaText(@"$\\ \vec{OB}$ is the vector followed to get from the origin $O$ to point $A$."); FormulaText(@"If $\vec{AB}=\bf{a}$, $\vec{BA}=\bf{-a}$.") ], 
shows up as:
![image](https://user-images.githubusercontent.com/45573905/57539318-25292500-7342-11e9-9cec-4051dcc2a64f.png)

I can't find a way to get the arrow to show up consistently while keeping all of the text in line.

**Comment by Happypig375** [comment]
This seems to be another example of #32.

**Comment by Happypig375** [comment]
Finally got around to fix this bug!

**Comment by Happypig375** [comment]
-> https://github.com/verybadcat/CSharpMath/blob/afa4fdeeb0e7e9d371efa10800981f4f241ad352/CSharpMath.SkiaSharp.Tests/Inline/VectorProjection.png
