### ISSUE TITLE
Creating fraction in an exponent produces additional symbols

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#39]
**To Reproduce**

1. Type `x`
2. Type `^`
3. Type `1`
4. Type `/`
5. Additional symbols are appered.

**Expected behavior**
There are no any additional symbols.

**Screenshots**

![gif](https://user-images.githubusercontent.com/16510738/62825692-87e7c200-bbb8-11e9-8e12-2cae84dcd736.gif)

**Comment by FoggyFinder** [comment]
I think the problem is [here](https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath.Editor/Keyboards/MathKeyboard.cs#L250):

```csharp
if (current.AtomIndex == _insertionIndex.AtomIndex) {
```

and [here](https://github.com/verybadcat/CSharpMath/blob/master/CSharpMath.Editor/Keyboards/MathKeyboard.cs#L264)

```csharp
MathList.RemoveAtoms(
              new MathListRange(current, _insertionIndex.AtomIndex - current.AtomIndex));
```

It looks a bit complicated. Isn't enough to use `numerator.Count`?

```csharp
if (numerator.Count == 0) {
```

```csharp
MathList.RemoveAtoms(new MathListRange(current, numerator.Count));
```

**Comment by Happypig375** [comment]
Cross-link to corresponding issue in MathEditor: https://github.com/kostub/MathEditor/issues/18
