### ISSUE TITLE
Exception on click if there is a placeholder

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#43]
**To Reproduce**

1. Create a fraction.
2. Move cursor after a placeholder via navigation arrow.
3. Type something.
4. Click there.
5. Exception.

**Expected behavior**

- No exception raised.
- Disallow to set insertedIndex after placeholder.

Not sure what fits better.

**Screenshots**

![gif](https://user-images.githubusercontent.com/16510738/63213735-92eea500-c118-11e9-9c6c-c63c179a2c48.gif)

**Comment by Happypig375** [comment]
Related to #48

**Comment by Happypig375** [comment]
Updated repro:
![image](https://i.imgur.com/xx4a6os.gif)
