### ISSUE TITLE
Round trip conversion leads to invalid LaTeX

### ISSUE THREAD

**Issue by Smurf-IV** [verybadcat/CSharpMath#59]
### Describe the bug
With the correct fix from #57, still get incorrect LaTeX

### To Reproduce
- Input is `\mathrm{Gap}^2`
![image](https://user-images.githubusercontent.com/2418812/64846935-bb799a00-d605-11e9-8f84-7910cd800c79.png)

- output from `MathListBuilder.MathListToString(mathList)` 
is `\mathrm{Gap^2}`

- Put this into the `MathListBuilder` -> `Build()` and it does not convert.

**Comment by charlesroddie** [comment]
It's possible this could be changed. Ideally before that, the purpose of getting a latex string from a mathlist should be decided.

Without speeding this out I do not see a bug here. TeX represents displayed mathematics. It does not necessarily represent what formulas mean. (For example `a(b+c)` could refer to multiplication or function application.) In your examples the input and the output TeX will be displayed the same way. So the simplification could be done in either step and is valid, unless we agree that specific non-visual information needs encoding inside mathlist or tex.

**Comment by Happypig375** [comment]
This is a bug in MathList->TeX code. If we use `\mathbf` instead of `\mathrm`, aka `\mathbf{Gap}^2\mathbf{gb}`, the 2 is not bolded and displays as so. However, when we convert the MathList back to TeX, it becomes `\mathbf{Gap^2gb}` and the 2 becomes bolded.

**Comment by Happypig375** [comment]
Fixed! Now the result is `\mathrm{Gap^{\mathnormal{2}}}` which is the true representation of `\mathrm{Gap}^2` in CSharpMath.
https://github.com/verybadcat/CSharpMath/blob/9fef1e1d5bc4ce656a1a716ee8c0abc3c567d1d8/CSharpMath.Tests/Atoms/LaTeXBuilderTest.cs#L638-L652
