### ISSUE TITLE
'\sqrt' throws

### ISSUE THREAD

**Issue by Happypig375** [verybadcat/CSharpMath#7]
Since CSharpMath looks for then next character after encountering a command, if the string ends there, an IndexOutOfRangeException will be thrown.

A fix is pending.

**Comment by Happypig375** [comment]
Consider opening an issue over at iosMath if this is really a bug.
Sent #8.

**Comment by verybadcat** [comment]
Are you good on it? If so, an example could be helpful. And you're more than welcome to write me at [my last name]@gmail.com for any reason.

**Comment by Happypig375** [comment]
I have since then also fixed a number of throws like this over at the SkiaSharp branch. I just wanted to maybe let you verify it. I have borrowed a Mac over and will verify this later if I remember to.
