### ISSUE TITLE
Hide caret when placeholder is in active state (black square)

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#71]
**Describe the solution you'd like**

No caret to the left side of the placeholder.

**Additional context**

Example of a current view:

![img](https://user-images.githubusercontent.com/19760720/68037352-7269cc00-fcbf-11e9-8e0e-1c6646ab3f9d.png)

**Comment by charlesroddie** [comment]
Now we have various fixes since the 0.3.0-beta (thanks @FoggyFinder ), @Happypig375 could you queue 0.3.0-beta2 please?

**Comment by FoggyFinder** [comment]
Maybe wait for one more day? I'm going to fix at least #51 today

**Comment by charlesroddie** [comment]
Is it quick to do a nuget release? Is thre an automated build that generates them in one step?

**Comment by charlesroddie** [comment]
Now #51 is in, can we have 0.3.0-beta2 please @Happypig375 ? Thanks!
