### ISSUE TITLE
Some math fonts not showing up in android device

### ISSUE THREAD

**Issue by hflexgrig** [verybadcat/CSharpMath#77]
![Screenshot_20191103-012304](https://user-images.githubusercontent.com/24684337/68078159-49d5f500-fdd9-11e9-9aa2-87f5c4ff8b80.jpg)

I know how to fix that, will make PR soon.

**Comment by hflexgrig** [comment]
Oops sorry, this is related to  <e:SvgButton StyleClass="Fraction"/> not the fonts, probably some dpi problems, i'll try to fix this tomorrow.

**Comment by hflexgrig** [comment]
On IOS there's no such problem. I've investigated little bit, seems like for android device, button's ImageSource not showing up any image. I even tried ImageSource.FromFile , ImageSource.FromUrl none of them worked.

**Comment by ImadAbuDev** [comment]
How do you use the equations or math font on your buttons like x or y. Can I see the code of one button?

**Comment by Happypig375** [comment]
Completely removed SVGs from CSharpMath.Forms.Example. All buttons now display math from MathPainter directly.
