### ISSUE TITLE
`sin^2` fails when getting LaTeX

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#85]
Steps to reproduce:
Enter `\sin^` in the Try part of the Forms example project, or attempt to enter `sin^2` in the Editor part.
Result:
```
Exception thrown: 'System.ArgumentNullException' in CSharpMath.dll
An exception of type 'System.ArgumentNullException' occurred in CSharpMath.dll but was not handled in user code
LaTeX Symbol name must not be null.
```
The atom gets constructed correctly, but getting latex fails.

Variables to powers and numbers to powers work, but functions to powers do not.

**Comment by charlesroddie** [comment]
`{Large Operator sin}` is cast to `op:LargeOperator` and `MathAtoms.LatexSymbolNameForAtom(op)` returns `null`.

**Comment by FoggyFinder** [comment]
Sounds like duplicate of #67
