### ISSUE TITLE
Squash merges + other branch policies

### ISSUE THREAD

**Issue by charlesroddie** [verybadcat/CSharpMath#91]
We should use squash merges.

Edit: also require changes to master through PRs as discussed below

**Comment by Happypig375** [comment]
Won't squash merges lose original commit history if the PR submitter decides to delete the old branch?

**Comment by charlesroddie** [comment]
Yes but that's rarely useful. Having many commits makes the history unreadable. You still get the history inside PRs and that's a more useful place to have it.

**Comment by Happypig375** [comment]
Ok then

**Comment by Happypig375** [comment]
Should we limit ourselves to squash merging?

**Comment by charlesroddie** [comment]
@Happypig375  @verybadcat  can we apply some branch and merge policies?

https://help.github.com/en/github/administering-a-repository/configuring-protected-branches
https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

I think these should be checked:

Branch policies on master:

- Require status checks to pass before merging
- Require linear history
- Include administrators

Merge button:

- Allow merge commits: no
- Allow squash commits: yes
- Allow rebase merging: no

**Comment by Happypig375** [comment]
I'm still thinking of the ability to debug into specific commits inside a pull request, doing `git bisect` inside a large PR (e.g. one that does a large refactor). Will this ability be lose?

**Comment by charlesroddie** [comment]
The ability would only be lost if you are analyzing commits in previous PRs where you have deleted the branch both on the server and locally.

Rationale for squash merges: https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/

**Comment by Happypig375** [comment]
>you have deleted the branch both on the server and locally.

When doing squash merges on GitHub, you press the merge button online and you won't clone the branch locally. On top of that, remote branches can be deleted by the pull requester (@FoggyFinder does this.)

**Comment by Happypig375** [comment]
>Rationale for squash merges: https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/

The mentioned benefits mainly revolve around manually looking at logs and doing `git blame`. I don't use that because any refactor will immediately diminish their effectiveness. I use `git bisect` instead.

**Comment by charlesroddie** [comment]
No the benefit is that every commit in master is proper: has a well done commit message, describes a  logical change, makes sense independently. The history of master then becomes understandable. You may be reading the "conclusion" section which is actually more of an appendix: try the main text instead.

>  remote branches can be deleted by the pull requester

Yes and this is common practice. I was thinking you were discussing debugging your own current and previous PRs to maintain a workflow. But it is actually possible to check out previous PRs and get the detailed inner commit history:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally
Referenced in https://stackoverflow.com/questions/56600553/does-github-retain-commit-history-for-squash-merged-prs-indefinitely

This would be fairly rare as a PR would describe a single piece of work, but could be used in niche cases where the process of creation of the PR needs to be brought back from the dead.

**Comment by siriak** [comment]
@Happypig375 for using `git bisect` you need every commit to, at least, build. It's often not the case as people are notorious for forgetting to put semicolon somewhere and doing other things that prevent WIP commits from compiling. That's especially true in the open-source community.

**Comment by Happypig375** [comment]
Should reviews be required for every PR?

**Comment by charlesroddie** [comment]
Probably at some later point. I don't think the repo is currently at the point where requiring reviews is possible. The stable part of it is but there is also an experimental part ongoing with symbolics.

That said, I'm happy to review prs that affect the rendering/editing/skiasharp parts of csharpmath.

**Comment by verybadcat** [comment]
Housekeeping suggestions have been done. Please let me know by email if any problems.

**Comment by Happypig375** [comment]
Closing as implemented

**Comment by charlesroddie** [comment]
It looks like commits direct to master are still possible. I'm finding it hard to determine the right settings from the github docs.

**Comment by Happypig375** [comment]
Thought you were only talking about PRs.

**Comment by charlesroddie** [comment]
@Happypig375 sorry you are right. I think it's good practice to have all changes to master via PRs. I omitted to mention that above and I'm not sure the right policy setting.

**Comment by charlesroddie** [comment]
We do need (@Happypig375 I was wrong about this one):

- Require PR reviews before merging

> https://github.community/t/best-practices-for-protected-branches/10204
> Don’t:  expect branch protection to prevent pushing commits which don’t alter the commit history. If you want to disable pushing directly to the branch, use the setting  Require pull request reviews before merging instead.

@verybadcat could you enable that please?

**Comment by Happypig375** [comment]
From @verybadcat:
<img width="1552" alt="CSharpMathRequiresReviews" src="https://user-images.githubusercontent.com/19922066/83263943-f4888780-a1f1-11ea-92c7-806182f2e471.png">
