### ISSUE TITLE
Remove placeholder in a base when one inserts in BetweenBaseAndScripts position

### ISSUE THREAD

**Issue by FoggyFinder** [verybadcat/CSharpMath#99]
**Describe the solution you'd like**

Placeholder is removed.

**Describe alternatives you've considered**

Dissallow ability to have insertionIndex in `BetweenBaseAndScripts` position if there is a placeholder.

**Difficulty: How difficult would it be? (Trivial, Very Easy, Easy, Moderate, Hard, Very Hard, Tedious, Backbreaking)**

Easy, I suppose

**Additional context**

![gif](https://user-images.githubusercontent.com/16510738/69475406-411f8000-0dd5-11ea-8059-233f851df4b6.gif)

Currently there are already 2 test-cases that failed because of that.

**Comment by Happypig375** [comment]
>Disallow ability to have insertionIndex in BetweenBaseAndScripts position if there is a placeholder.

This may be better as semantically there is nothing in the base, thus after pointing to the base, there is no "space after nothing" and the insertion index directly goes to the scripts.

**Comment by charlesroddie** [comment]
> Dissallow ability to have insertionIndex in BetweenBaseAndScripts position if there is a placeholder.

I agree with this. You shouldn't be able to position the cursor in between in your screenshot.

**Comment by charlesroddie** [comment]
The random test (which searches for the simplest keyboard input that crashes the editor) now gives more complex examples:
```
[Sine; Power; Left; BothRoundBrackets; Equals; Sine]
[A; Subscript; Left; BothRoundBrackets; BothRoundBrackets]
[A; Subscript; Left; BothRoundBrackets; Minus; C]
```

**Comment by FoggyFinder** [comment]
Yep, I had noticed it too and mentioned in PR. Seems unrelated to this issue.

Needs to open another one. I can do it later.
